// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongxsd/test/reqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_A_DATATYPE_DEFINITION_STRING_REF_sql sql.NullBool
var dummy_A_DATATYPE_DEFINITION_STRING_REF_time time.Duration
var dummy_A_DATATYPE_DEFINITION_STRING_REF_sort sort.Float64Slice

// A_DATATYPE_DEFINITION_STRING_REFAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model a_datatype_definition_string_refAPI
type A_DATATYPE_DEFINITION_STRING_REFAPI struct {
	gorm.Model

	models.A_DATATYPE_DEFINITION_STRING_REF_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	A_DATATYPE_DEFINITION_STRING_REFPointersEncoding A_DATATYPE_DEFINITION_STRING_REFPointersEncoding
}

// A_DATATYPE_DEFINITION_STRING_REFPointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type A_DATATYPE_DEFINITION_STRING_REFPointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// A_DATATYPE_DEFINITION_STRING_REFDB describes a a_datatype_definition_string_ref in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model a_datatype_definition_string_refDB
type A_DATATYPE_DEFINITION_STRING_REFDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field a_datatype_definition_string_refDB.Name
	Name_Data sql.NullString

	// Declation for basic field a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF
	DATATYPE_DEFINITION_STRING_REF_Data sql.NullString
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	A_DATATYPE_DEFINITION_STRING_REFPointersEncoding
}

// A_DATATYPE_DEFINITION_STRING_REFDBs arrays a_datatype_definition_string_refDBs
// swagger:response a_datatype_definition_string_refDBsResponse
type A_DATATYPE_DEFINITION_STRING_REFDBs []A_DATATYPE_DEFINITION_STRING_REFDB

// A_DATATYPE_DEFINITION_STRING_REFDBResponse provides response
// swagger:response a_datatype_definition_string_refDBResponse
type A_DATATYPE_DEFINITION_STRING_REFDBResponse struct {
	A_DATATYPE_DEFINITION_STRING_REFDB
}

// A_DATATYPE_DEFINITION_STRING_REFWOP is a A_DATATYPE_DEFINITION_STRING_REF without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type A_DATATYPE_DEFINITION_STRING_REFWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	DATATYPE_DEFINITION_STRING_REF string `xlsx:"2"`
	// insertion for WOP pointer fields
}

var A_DATATYPE_DEFINITION_STRING_REF_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"DATATYPE_DEFINITION_STRING_REF",
}

type BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct struct {
	// stores A_DATATYPE_DEFINITION_STRING_REFDB according to their gorm ID
	Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB map[uint]*A_DATATYPE_DEFINITION_STRING_REFDB

	// stores A_DATATYPE_DEFINITION_STRING_REFDB ID according to A_DATATYPE_DEFINITION_STRING_REF address
	Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID map[*models.A_DATATYPE_DEFINITION_STRING_REF]uint

	// stores A_DATATYPE_DEFINITION_STRING_REF according to their gorm ID
	Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr map[uint]*models.A_DATATYPE_DEFINITION_STRING_REF

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) GetStage() (stage *models.StageStruct) {
	stage = backRepoA_DATATYPE_DEFINITION_STRING_REF.stage
	return
}

func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) GetDB() *gorm.DB {
	return backRepoA_DATATYPE_DEFINITION_STRING_REF.db
}

// GetA_DATATYPE_DEFINITION_STRING_REFDBFromA_DATATYPE_DEFINITION_STRING_REFPtr is a handy function to access the back repo instance from the stage instance
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) GetA_DATATYPE_DEFINITION_STRING_REFDBFromA_DATATYPE_DEFINITION_STRING_REFPtr(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) {
	id := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref]
	a_datatype_definition_string_refDB = backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[id]
	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseOne commits all staged instances of A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for a_datatype_definition_string_ref := range stage.A_DATATYPE_DEFINITION_STRING_REFs {
		backRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseOneInstance(a_datatype_definition_string_ref)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, a_datatype_definition_string_ref := range backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr {
		if _, ok := stage.A_DATATYPE_DEFINITION_STRING_REFs[a_datatype_definition_string_ref]; !ok {
			backRepoA_DATATYPE_DEFINITION_STRING_REF.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CommitDeleteInstance commits deletion of A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CommitDeleteInstance(id uint) (Error error) {

	a_datatype_definition_string_ref := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr[id]

	// a_datatype_definition_string_ref is not staged anymore, remove a_datatype_definition_string_refDB
	a_datatype_definition_string_refDB := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[id]
	query := backRepoA_DATATYPE_DEFINITION_STRING_REF.db.Unscoped().Delete(&a_datatype_definition_string_refDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID, a_datatype_definition_string_ref)
	delete(backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr, id)
	delete(backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB, id)

	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseOneInstance commits a_datatype_definition_string_ref staged instances of A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CommitPhaseOneInstance(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) (Error error) {

	// check if the a_datatype_definition_string_ref is not commited yet
	if _, ok := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref]; ok {
		return
	}

	// initiate a_datatype_definition_string_ref
	var a_datatype_definition_string_refDB A_DATATYPE_DEFINITION_STRING_REFDB
	a_datatype_definition_string_refDB.CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REF(a_datatype_definition_string_ref)

	query := backRepoA_DATATYPE_DEFINITION_STRING_REF.db.Create(&a_datatype_definition_string_refDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref] = a_datatype_definition_string_refDB.ID
	backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr[a_datatype_definition_string_refDB.ID] = a_datatype_definition_string_ref
	backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[a_datatype_definition_string_refDB.ID] = &a_datatype_definition_string_refDB

	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseTwo commits all staged instances of A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, a_datatype_definition_string_ref := range backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr {
		backRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseTwoInstance(backRepo, idx, a_datatype_definition_string_ref)
	}

	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseTwoInstance commits {{structname }} of models.A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) (Error error) {

	// fetch matching a_datatype_definition_string_refDB
	if a_datatype_definition_string_refDB, ok := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[idx]; ok {

		a_datatype_definition_string_refDB.CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REF(a_datatype_definition_string_ref)

		// insertion point for translating pointers encodings into actual pointers
		query := backRepoA_DATATYPE_DEFINITION_STRING_REF.db.Save(&a_datatype_definition_string_refDB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown A_DATATYPE_DEFINITION_STRING_REF intance %s", a_datatype_definition_string_ref.Name))
		return err
	}

	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CheckoutPhaseOne() (Error error) {

	a_datatype_definition_string_refDBArray := make([]A_DATATYPE_DEFINITION_STRING_REFDB, 0)
	query := backRepoA_DATATYPE_DEFINITION_STRING_REF.db.Find(&a_datatype_definition_string_refDBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	a_datatype_definition_string_refInstancesToBeRemovedFromTheStage := make(map[*models.A_DATATYPE_DEFINITION_STRING_REF]any)
	for key, value := range backRepoA_DATATYPE_DEFINITION_STRING_REF.stage.A_DATATYPE_DEFINITION_STRING_REFs {
		a_datatype_definition_string_refInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, a_datatype_definition_string_refDB := range a_datatype_definition_string_refDBArray {
		backRepoA_DATATYPE_DEFINITION_STRING_REF.CheckoutPhaseOneInstance(&a_datatype_definition_string_refDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		a_datatype_definition_string_ref, ok := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr[a_datatype_definition_string_refDB.ID]
		if ok {
			delete(a_datatype_definition_string_refInstancesToBeRemovedFromTheStage, a_datatype_definition_string_ref)
		}
	}

	// remove from stage and back repo's 3 maps all a_datatype_definition_string_refs that are not in the checkout
	for a_datatype_definition_string_ref := range a_datatype_definition_string_refInstancesToBeRemovedFromTheStage {
		a_datatype_definition_string_ref.Unstage(backRepoA_DATATYPE_DEFINITION_STRING_REF.GetStage())

		// remove instance from the back repo 3 maps
		a_datatype_definition_string_refID := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref]
		delete(backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID, a_datatype_definition_string_ref)
		delete(backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB, a_datatype_definition_string_refID)
		delete(backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr, a_datatype_definition_string_refID)
	}

	return
}

// CheckoutPhaseOneInstance takes a a_datatype_definition_string_refDB that has been found in the DB, updates the backRepo and stages the
// models version of the a_datatype_definition_string_refDB
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CheckoutPhaseOneInstance(a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) (Error error) {

	a_datatype_definition_string_ref, ok := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr[a_datatype_definition_string_refDB.ID]
	if !ok {
		a_datatype_definition_string_ref = new(models.A_DATATYPE_DEFINITION_STRING_REF)

		backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr[a_datatype_definition_string_refDB.ID] = a_datatype_definition_string_ref
		backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref] = a_datatype_definition_string_refDB.ID

		// append model store with the new element
		a_datatype_definition_string_ref.Name = a_datatype_definition_string_refDB.Name_Data.String
		a_datatype_definition_string_ref.Stage(backRepoA_DATATYPE_DEFINITION_STRING_REF.GetStage())
	}
	a_datatype_definition_string_refDB.CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REF(a_datatype_definition_string_ref)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	a_datatype_definition_string_ref.Stage(backRepoA_DATATYPE_DEFINITION_STRING_REF.GetStage())

	// preserve pointer to a_datatype_definition_string_refDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB)[a_datatype_definition_string_refDB hold variable pointers
	a_datatype_definition_string_refDB_Data := *a_datatype_definition_string_refDB
	preservedPtrToA_DATATYPE_DEFINITION_STRING_REF := &a_datatype_definition_string_refDB_Data
	backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[a_datatype_definition_string_refDB.ID] = preservedPtrToA_DATATYPE_DEFINITION_STRING_REF

	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CheckoutPhaseTwo Checkouts all staged instances of A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, a_datatype_definition_string_refDB := range backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB {
		backRepoA_DATATYPE_DEFINITION_STRING_REF.CheckoutPhaseTwoInstance(backRepo, a_datatype_definition_string_refDB)
	}
	return
}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.CheckoutPhaseTwoInstance Checkouts staged instances of A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) (Error error) {

	a_datatype_definition_string_ref := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr[a_datatype_definition_string_refDB.ID]

	a_datatype_definition_string_refDB.DecodePointers(backRepo, a_datatype_definition_string_ref)

	return
}

func (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) DecodePointers(backRepo *BackRepoStruct, a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitA_DATATYPE_DEFINITION_STRING_REF allows commit of a single a_datatype_definition_string_ref (if already staged)
func (backRepo *BackRepoStruct) CommitA_DATATYPE_DEFINITION_STRING_REF(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) {
	backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseOneInstance(a_datatype_definition_string_ref)
	if id, ok := backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref]; ok {
		backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.CommitPhaseTwoInstance(backRepo, id, a_datatype_definition_string_ref)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitA_DATATYPE_DEFINITION_STRING_REF allows checkout of a single a_datatype_definition_string_ref (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutA_DATATYPE_DEFINITION_STRING_REF(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) {
	// check if the a_datatype_definition_string_ref is staged
	if _, ok := backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref]; ok {

		if id, ok := backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFPtr_A_DATATYPE_DEFINITION_STRING_REFDBID[a_datatype_definition_string_ref]; ok {
			var a_datatype_definition_string_refDB A_DATATYPE_DEFINITION_STRING_REFDB
			a_datatype_definition_string_refDB.ID = id

			if err := backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.db.First(&a_datatype_definition_string_refDB, id).Error; err != nil {
				log.Fatalln("CheckoutA_DATATYPE_DEFINITION_STRING_REF : Problem with getting object with id:", id)
			}
			backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.CheckoutPhaseOneInstance(&a_datatype_definition_string_refDB)
			backRepo.BackRepoA_DATATYPE_DEFINITION_STRING_REF.CheckoutPhaseTwoInstance(backRepo, &a_datatype_definition_string_refDB)
		}
	}
}

// CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REF
func (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REF(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) {
	// insertion point for fields commit

	a_datatype_definition_string_refDB.Name_Data.String = a_datatype_definition_string_ref.Name
	a_datatype_definition_string_refDB.Name_Data.Valid = true

	a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.String = a_datatype_definition_string_ref.DATATYPE_DEFINITION_STRING_REF
	a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REF_WOP
func (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REF_WOP(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF_WOP) {
	// insertion point for fields commit

	a_datatype_definition_string_refDB.Name_Data.String = a_datatype_definition_string_ref.Name
	a_datatype_definition_string_refDB.Name_Data.Valid = true

	a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.String = a_datatype_definition_string_ref.DATATYPE_DEFINITION_STRING_REF
	a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REFWOP
func (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REFWOP(a_datatype_definition_string_ref *A_DATATYPE_DEFINITION_STRING_REFWOP) {
	// insertion point for fields commit

	a_datatype_definition_string_refDB.Name_Data.String = a_datatype_definition_string_ref.Name
	a_datatype_definition_string_refDB.Name_Data.Valid = true

	a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.String = a_datatype_definition_string_ref.DATATYPE_DEFINITION_STRING_REF
	a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.Valid = true
}

// CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REF
func (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REF(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_datatype_definition_string_ref.Name = a_datatype_definition_string_refDB.Name_Data.String
	a_datatype_definition_string_ref.DATATYPE_DEFINITION_STRING_REF = a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.String
}

// CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REF_WOP
func (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REF_WOP(a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_datatype_definition_string_ref.Name = a_datatype_definition_string_refDB.Name_Data.String
	a_datatype_definition_string_ref.DATATYPE_DEFINITION_STRING_REF = a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.String
}

// CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REFWOP
func (a_datatype_definition_string_refDB *A_DATATYPE_DEFINITION_STRING_REFDB) CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REFWOP(a_datatype_definition_string_ref *A_DATATYPE_DEFINITION_STRING_REFWOP) {
	a_datatype_definition_string_ref.ID = int(a_datatype_definition_string_refDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	a_datatype_definition_string_ref.Name = a_datatype_definition_string_refDB.Name_Data.String
	a_datatype_definition_string_ref.DATATYPE_DEFINITION_STRING_REF = a_datatype_definition_string_refDB.DATATYPE_DEFINITION_STRING_REF_Data.String
}

// Backup generates a json file from a slice of all A_DATATYPE_DEFINITION_STRING_REFDB instances in the backrepo
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "A_DATATYPE_DEFINITION_STRING_REFDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_DATATYPE_DEFINITION_STRING_REFDB, 0)
	for _, a_datatype_definition_string_refDB := range backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB {
		forBackup = append(forBackup, a_datatype_definition_string_refDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json A_DATATYPE_DEFINITION_STRING_REF ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json A_DATATYPE_DEFINITION_STRING_REF file", err.Error())
	}
}

// Backup generates a json file from a slice of all A_DATATYPE_DEFINITION_STRING_REFDB instances in the backrepo
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_DATATYPE_DEFINITION_STRING_REFDB, 0)
	for _, a_datatype_definition_string_refDB := range backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB {
		forBackup = append(forBackup, a_datatype_definition_string_refDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("A_DATATYPE_DEFINITION_STRING_REF")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&A_DATATYPE_DEFINITION_STRING_REF_Fields, -1)
	for _, a_datatype_definition_string_refDB := range forBackup {

		var a_datatype_definition_string_refWOP A_DATATYPE_DEFINITION_STRING_REFWOP
		a_datatype_definition_string_refDB.CopyBasicFieldsToA_DATATYPE_DEFINITION_STRING_REFWOP(&a_datatype_definition_string_refWOP)

		row := sh.AddRow()
		row.WriteStruct(&a_datatype_definition_string_refWOP, -1)
	}
}

// RestoreXL from the "A_DATATYPE_DEFINITION_STRING_REF" sheet all A_DATATYPE_DEFINITION_STRING_REFDB instances
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoA_DATATYPE_DEFINITION_STRING_REFid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["A_DATATYPE_DEFINITION_STRING_REF"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoA_DATATYPE_DEFINITION_STRING_REF.rowVisitorA_DATATYPE_DEFINITION_STRING_REF)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) rowVisitorA_DATATYPE_DEFINITION_STRING_REF(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var a_datatype_definition_string_refWOP A_DATATYPE_DEFINITION_STRING_REFWOP
		row.ReadStruct(&a_datatype_definition_string_refWOP)

		// add the unmarshalled struct to the stage
		a_datatype_definition_string_refDB := new(A_DATATYPE_DEFINITION_STRING_REFDB)
		a_datatype_definition_string_refDB.CopyBasicFieldsFromA_DATATYPE_DEFINITION_STRING_REFWOP(&a_datatype_definition_string_refWOP)

		a_datatype_definition_string_refDB_ID_atBackupTime := a_datatype_definition_string_refDB.ID
		a_datatype_definition_string_refDB.ID = 0
		query := backRepoA_DATATYPE_DEFINITION_STRING_REF.db.Create(a_datatype_definition_string_refDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[a_datatype_definition_string_refDB.ID] = a_datatype_definition_string_refDB
		BackRepoA_DATATYPE_DEFINITION_STRING_REFid_atBckpTime_newID[a_datatype_definition_string_refDB_ID_atBackupTime] = a_datatype_definition_string_refDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "A_DATATYPE_DEFINITION_STRING_REFDB.json" in dirPath that stores an array
// of A_DATATYPE_DEFINITION_STRING_REFDB and stores it in the database
// the map BackRepoA_DATATYPE_DEFINITION_STRING_REFid_atBckpTime_newID is updated accordingly
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoA_DATATYPE_DEFINITION_STRING_REFid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "A_DATATYPE_DEFINITION_STRING_REFDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json A_DATATYPE_DEFINITION_STRING_REF file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*A_DATATYPE_DEFINITION_STRING_REFDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB
	for _, a_datatype_definition_string_refDB := range forRestore {

		a_datatype_definition_string_refDB_ID_atBackupTime := a_datatype_definition_string_refDB.ID
		a_datatype_definition_string_refDB.ID = 0
		query := backRepoA_DATATYPE_DEFINITION_STRING_REF.db.Create(a_datatype_definition_string_refDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[a_datatype_definition_string_refDB.ID] = a_datatype_definition_string_refDB
		BackRepoA_DATATYPE_DEFINITION_STRING_REFid_atBckpTime_newID[a_datatype_definition_string_refDB_ID_atBackupTime] = a_datatype_definition_string_refDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json A_DATATYPE_DEFINITION_STRING_REF file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<A_DATATYPE_DEFINITION_STRING_REF>id_atBckpTime_newID
// to compute new index
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) RestorePhaseTwo() {

	for _, a_datatype_definition_string_refDB := range backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB {

		// next line of code is to avert unused variable compilation error
		_ = a_datatype_definition_string_refDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		query := backRepoA_DATATYPE_DEFINITION_STRING_REF.db.Model(a_datatype_definition_string_refDB).Updates(*a_datatype_definition_string_refDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoA_DATATYPE_DEFINITION_STRING_REF.ResetReversePointers commits all staged instances of A_DATATYPE_DEFINITION_STRING_REF to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, a_datatype_definition_string_ref := range backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFPtr {
		backRepoA_DATATYPE_DEFINITION_STRING_REF.ResetReversePointersInstance(backRepo, idx, a_datatype_definition_string_ref)
	}

	return
}

func (backRepoA_DATATYPE_DEFINITION_STRING_REF *BackRepoA_DATATYPE_DEFINITION_STRING_REFStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, a_datatype_definition_string_ref *models.A_DATATYPE_DEFINITION_STRING_REF) (Error error) {

	// fetch matching a_datatype_definition_string_refDB
	if a_datatype_definition_string_refDB, ok := backRepoA_DATATYPE_DEFINITION_STRING_REF.Map_A_DATATYPE_DEFINITION_STRING_REFDBID_A_DATATYPE_DEFINITION_STRING_REFDB[idx]; ok {
		_ = a_datatype_definition_string_refDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoA_DATATYPE_DEFINITION_STRING_REFid_atBckpTime_newID map[uint]uint
