// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongxsd/test/reqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_A_DEFINITION_4_sql sql.NullBool
var dummy_A_DEFINITION_4_time time.Duration
var dummy_A_DEFINITION_4_sort sort.Float64Slice

// A_DEFINITION_4API is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model a_definition_4API
type A_DEFINITION_4API struct {
	gorm.Model

	models.A_DEFINITION_4_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	A_DEFINITION_4PointersEncoding A_DEFINITION_4PointersEncoding
}

// A_DEFINITION_4PointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type A_DEFINITION_4PointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// A_DEFINITION_4DB describes a a_definition_4 in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model a_definition_4DB
type A_DEFINITION_4DB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field a_definition_4DB.Name
	Name_Data sql.NullString

	// Declation for basic field a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF
	ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data sql.NullString
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	A_DEFINITION_4PointersEncoding
}

// A_DEFINITION_4DBs arrays a_definition_4DBs
// swagger:response a_definition_4DBsResponse
type A_DEFINITION_4DBs []A_DEFINITION_4DB

// A_DEFINITION_4DBResponse provides response
// swagger:response a_definition_4DBResponse
type A_DEFINITION_4DBResponse struct {
	A_DEFINITION_4DB
}

// A_DEFINITION_4WOP is a A_DEFINITION_4 without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type A_DEFINITION_4WOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	ATTRIBUTE_DEFINITION_BOOLEAN_REF string `xlsx:"2"`
	// insertion for WOP pointer fields
}

var A_DEFINITION_4_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"ATTRIBUTE_DEFINITION_BOOLEAN_REF",
}

type BackRepoA_DEFINITION_4Struct struct {
	// stores A_DEFINITION_4DB according to their gorm ID
	Map_A_DEFINITION_4DBID_A_DEFINITION_4DB map[uint]*A_DEFINITION_4DB

	// stores A_DEFINITION_4DB ID according to A_DEFINITION_4 address
	Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID map[*models.A_DEFINITION_4]uint

	// stores A_DEFINITION_4 according to their gorm ID
	Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr map[uint]*models.A_DEFINITION_4

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) GetStage() (stage *models.StageStruct) {
	stage = backRepoA_DEFINITION_4.stage
	return
}

func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) GetDB() *gorm.DB {
	return backRepoA_DEFINITION_4.db
}

// GetA_DEFINITION_4DBFromA_DEFINITION_4Ptr is a handy function to access the back repo instance from the stage instance
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) GetA_DEFINITION_4DBFromA_DEFINITION_4Ptr(a_definition_4 *models.A_DEFINITION_4) (a_definition_4DB *A_DEFINITION_4DB) {
	id := backRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4]
	a_definition_4DB = backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[id]
	return
}

// BackRepoA_DEFINITION_4.CommitPhaseOne commits all staged instances of A_DEFINITION_4 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for a_definition_4 := range stage.A_DEFINITION_4s {
		backRepoA_DEFINITION_4.CommitPhaseOneInstance(a_definition_4)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, a_definition_4 := range backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr {
		if _, ok := stage.A_DEFINITION_4s[a_definition_4]; !ok {
			backRepoA_DEFINITION_4.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoA_DEFINITION_4.CommitDeleteInstance commits deletion of A_DEFINITION_4 to the BackRepo
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CommitDeleteInstance(id uint) (Error error) {

	a_definition_4 := backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr[id]

	// a_definition_4 is not staged anymore, remove a_definition_4DB
	a_definition_4DB := backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[id]
	query := backRepoA_DEFINITION_4.db.Unscoped().Delete(&a_definition_4DB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID, a_definition_4)
	delete(backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr, id)
	delete(backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB, id)

	return
}

// BackRepoA_DEFINITION_4.CommitPhaseOneInstance commits a_definition_4 staged instances of A_DEFINITION_4 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CommitPhaseOneInstance(a_definition_4 *models.A_DEFINITION_4) (Error error) {

	// check if the a_definition_4 is not commited yet
	if _, ok := backRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4]; ok {
		return
	}

	// initiate a_definition_4
	var a_definition_4DB A_DEFINITION_4DB
	a_definition_4DB.CopyBasicFieldsFromA_DEFINITION_4(a_definition_4)

	query := backRepoA_DEFINITION_4.db.Create(&a_definition_4DB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4] = a_definition_4DB.ID
	backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr[a_definition_4DB.ID] = a_definition_4
	backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[a_definition_4DB.ID] = &a_definition_4DB

	return
}

// BackRepoA_DEFINITION_4.CommitPhaseTwo commits all staged instances of A_DEFINITION_4 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, a_definition_4 := range backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr {
		backRepoA_DEFINITION_4.CommitPhaseTwoInstance(backRepo, idx, a_definition_4)
	}

	return
}

// BackRepoA_DEFINITION_4.CommitPhaseTwoInstance commits {{structname }} of models.A_DEFINITION_4 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, a_definition_4 *models.A_DEFINITION_4) (Error error) {

	// fetch matching a_definition_4DB
	if a_definition_4DB, ok := backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[idx]; ok {

		a_definition_4DB.CopyBasicFieldsFromA_DEFINITION_4(a_definition_4)

		// insertion point for translating pointers encodings into actual pointers
		query := backRepoA_DEFINITION_4.db.Save(&a_definition_4DB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown A_DEFINITION_4 intance %s", a_definition_4.Name))
		return err
	}

	return
}

// BackRepoA_DEFINITION_4.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CheckoutPhaseOne() (Error error) {

	a_definition_4DBArray := make([]A_DEFINITION_4DB, 0)
	query := backRepoA_DEFINITION_4.db.Find(&a_definition_4DBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	a_definition_4InstancesToBeRemovedFromTheStage := make(map[*models.A_DEFINITION_4]any)
	for key, value := range backRepoA_DEFINITION_4.stage.A_DEFINITION_4s {
		a_definition_4InstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, a_definition_4DB := range a_definition_4DBArray {
		backRepoA_DEFINITION_4.CheckoutPhaseOneInstance(&a_definition_4DB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		a_definition_4, ok := backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr[a_definition_4DB.ID]
		if ok {
			delete(a_definition_4InstancesToBeRemovedFromTheStage, a_definition_4)
		}
	}

	// remove from stage and back repo's 3 maps all a_definition_4s that are not in the checkout
	for a_definition_4 := range a_definition_4InstancesToBeRemovedFromTheStage {
		a_definition_4.Unstage(backRepoA_DEFINITION_4.GetStage())

		// remove instance from the back repo 3 maps
		a_definition_4ID := backRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4]
		delete(backRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID, a_definition_4)
		delete(backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB, a_definition_4ID)
		delete(backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr, a_definition_4ID)
	}

	return
}

// CheckoutPhaseOneInstance takes a a_definition_4DB that has been found in the DB, updates the backRepo and stages the
// models version of the a_definition_4DB
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CheckoutPhaseOneInstance(a_definition_4DB *A_DEFINITION_4DB) (Error error) {

	a_definition_4, ok := backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr[a_definition_4DB.ID]
	if !ok {
		a_definition_4 = new(models.A_DEFINITION_4)

		backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr[a_definition_4DB.ID] = a_definition_4
		backRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4] = a_definition_4DB.ID

		// append model store with the new element
		a_definition_4.Name = a_definition_4DB.Name_Data.String
		a_definition_4.Stage(backRepoA_DEFINITION_4.GetStage())
	}
	a_definition_4DB.CopyBasicFieldsToA_DEFINITION_4(a_definition_4)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	a_definition_4.Stage(backRepoA_DEFINITION_4.GetStage())

	// preserve pointer to a_definition_4DB. Otherwise, pointer will is recycled and the map of pointers
	// Map_A_DEFINITION_4DBID_A_DEFINITION_4DB)[a_definition_4DB hold variable pointers
	a_definition_4DB_Data := *a_definition_4DB
	preservedPtrToA_DEFINITION_4 := &a_definition_4DB_Data
	backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[a_definition_4DB.ID] = preservedPtrToA_DEFINITION_4

	return
}

// BackRepoA_DEFINITION_4.CheckoutPhaseTwo Checkouts all staged instances of A_DEFINITION_4 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, a_definition_4DB := range backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB {
		backRepoA_DEFINITION_4.CheckoutPhaseTwoInstance(backRepo, a_definition_4DB)
	}
	return
}

// BackRepoA_DEFINITION_4.CheckoutPhaseTwoInstance Checkouts staged instances of A_DEFINITION_4 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, a_definition_4DB *A_DEFINITION_4DB) (Error error) {

	a_definition_4 := backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr[a_definition_4DB.ID]

	a_definition_4DB.DecodePointers(backRepo, a_definition_4)

	return
}

func (a_definition_4DB *A_DEFINITION_4DB) DecodePointers(backRepo *BackRepoStruct, a_definition_4 *models.A_DEFINITION_4) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitA_DEFINITION_4 allows commit of a single a_definition_4 (if already staged)
func (backRepo *BackRepoStruct) CommitA_DEFINITION_4(a_definition_4 *models.A_DEFINITION_4) {
	backRepo.BackRepoA_DEFINITION_4.CommitPhaseOneInstance(a_definition_4)
	if id, ok := backRepo.BackRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4]; ok {
		backRepo.BackRepoA_DEFINITION_4.CommitPhaseTwoInstance(backRepo, id, a_definition_4)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitA_DEFINITION_4 allows checkout of a single a_definition_4 (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutA_DEFINITION_4(a_definition_4 *models.A_DEFINITION_4) {
	// check if the a_definition_4 is staged
	if _, ok := backRepo.BackRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4]; ok {

		if id, ok := backRepo.BackRepoA_DEFINITION_4.Map_A_DEFINITION_4Ptr_A_DEFINITION_4DBID[a_definition_4]; ok {
			var a_definition_4DB A_DEFINITION_4DB
			a_definition_4DB.ID = id

			if err := backRepo.BackRepoA_DEFINITION_4.db.First(&a_definition_4DB, id).Error; err != nil {
				log.Fatalln("CheckoutA_DEFINITION_4 : Problem with getting object with id:", id)
			}
			backRepo.BackRepoA_DEFINITION_4.CheckoutPhaseOneInstance(&a_definition_4DB)
			backRepo.BackRepoA_DEFINITION_4.CheckoutPhaseTwoInstance(backRepo, &a_definition_4DB)
		}
	}
}

// CopyBasicFieldsFromA_DEFINITION_4
func (a_definition_4DB *A_DEFINITION_4DB) CopyBasicFieldsFromA_DEFINITION_4(a_definition_4 *models.A_DEFINITION_4) {
	// insertion point for fields commit

	a_definition_4DB.Name_Data.String = a_definition_4.Name
	a_definition_4DB.Name_Data.Valid = true

	a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.String = a_definition_4.ATTRIBUTE_DEFINITION_BOOLEAN_REF
	a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_DEFINITION_4_WOP
func (a_definition_4DB *A_DEFINITION_4DB) CopyBasicFieldsFromA_DEFINITION_4_WOP(a_definition_4 *models.A_DEFINITION_4_WOP) {
	// insertion point for fields commit

	a_definition_4DB.Name_Data.String = a_definition_4.Name
	a_definition_4DB.Name_Data.Valid = true

	a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.String = a_definition_4.ATTRIBUTE_DEFINITION_BOOLEAN_REF
	a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_DEFINITION_4WOP
func (a_definition_4DB *A_DEFINITION_4DB) CopyBasicFieldsFromA_DEFINITION_4WOP(a_definition_4 *A_DEFINITION_4WOP) {
	// insertion point for fields commit

	a_definition_4DB.Name_Data.String = a_definition_4.Name
	a_definition_4DB.Name_Data.Valid = true

	a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.String = a_definition_4.ATTRIBUTE_DEFINITION_BOOLEAN_REF
	a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.Valid = true
}

// CopyBasicFieldsToA_DEFINITION_4
func (a_definition_4DB *A_DEFINITION_4DB) CopyBasicFieldsToA_DEFINITION_4(a_definition_4 *models.A_DEFINITION_4) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_definition_4.Name = a_definition_4DB.Name_Data.String
	a_definition_4.ATTRIBUTE_DEFINITION_BOOLEAN_REF = a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.String
}

// CopyBasicFieldsToA_DEFINITION_4_WOP
func (a_definition_4DB *A_DEFINITION_4DB) CopyBasicFieldsToA_DEFINITION_4_WOP(a_definition_4 *models.A_DEFINITION_4_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_definition_4.Name = a_definition_4DB.Name_Data.String
	a_definition_4.ATTRIBUTE_DEFINITION_BOOLEAN_REF = a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.String
}

// CopyBasicFieldsToA_DEFINITION_4WOP
func (a_definition_4DB *A_DEFINITION_4DB) CopyBasicFieldsToA_DEFINITION_4WOP(a_definition_4 *A_DEFINITION_4WOP) {
	a_definition_4.ID = int(a_definition_4DB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	a_definition_4.Name = a_definition_4DB.Name_Data.String
	a_definition_4.ATTRIBUTE_DEFINITION_BOOLEAN_REF = a_definition_4DB.ATTRIBUTE_DEFINITION_BOOLEAN_REF_Data.String
}

// Backup generates a json file from a slice of all A_DEFINITION_4DB instances in the backrepo
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "A_DEFINITION_4DB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_DEFINITION_4DB, 0)
	for _, a_definition_4DB := range backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB {
		forBackup = append(forBackup, a_definition_4DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json A_DEFINITION_4 ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json A_DEFINITION_4 file", err.Error())
	}
}

// Backup generates a json file from a slice of all A_DEFINITION_4DB instances in the backrepo
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_DEFINITION_4DB, 0)
	for _, a_definition_4DB := range backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB {
		forBackup = append(forBackup, a_definition_4DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("A_DEFINITION_4")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&A_DEFINITION_4_Fields, -1)
	for _, a_definition_4DB := range forBackup {

		var a_definition_4WOP A_DEFINITION_4WOP
		a_definition_4DB.CopyBasicFieldsToA_DEFINITION_4WOP(&a_definition_4WOP)

		row := sh.AddRow()
		row.WriteStruct(&a_definition_4WOP, -1)
	}
}

// RestoreXL from the "A_DEFINITION_4" sheet all A_DEFINITION_4DB instances
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoA_DEFINITION_4id_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["A_DEFINITION_4"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoA_DEFINITION_4.rowVisitorA_DEFINITION_4)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) rowVisitorA_DEFINITION_4(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var a_definition_4WOP A_DEFINITION_4WOP
		row.ReadStruct(&a_definition_4WOP)

		// add the unmarshalled struct to the stage
		a_definition_4DB := new(A_DEFINITION_4DB)
		a_definition_4DB.CopyBasicFieldsFromA_DEFINITION_4WOP(&a_definition_4WOP)

		a_definition_4DB_ID_atBackupTime := a_definition_4DB.ID
		a_definition_4DB.ID = 0
		query := backRepoA_DEFINITION_4.db.Create(a_definition_4DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[a_definition_4DB.ID] = a_definition_4DB
		BackRepoA_DEFINITION_4id_atBckpTime_newID[a_definition_4DB_ID_atBackupTime] = a_definition_4DB.ID
	}
	return nil
}

// RestorePhaseOne read the file "A_DEFINITION_4DB.json" in dirPath that stores an array
// of A_DEFINITION_4DB and stores it in the database
// the map BackRepoA_DEFINITION_4id_atBckpTime_newID is updated accordingly
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoA_DEFINITION_4id_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "A_DEFINITION_4DB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json A_DEFINITION_4 file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*A_DEFINITION_4DB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_A_DEFINITION_4DBID_A_DEFINITION_4DB
	for _, a_definition_4DB := range forRestore {

		a_definition_4DB_ID_atBackupTime := a_definition_4DB.ID
		a_definition_4DB.ID = 0
		query := backRepoA_DEFINITION_4.db.Create(a_definition_4DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[a_definition_4DB.ID] = a_definition_4DB
		BackRepoA_DEFINITION_4id_atBckpTime_newID[a_definition_4DB_ID_atBackupTime] = a_definition_4DB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json A_DEFINITION_4 file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<A_DEFINITION_4>id_atBckpTime_newID
// to compute new index
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) RestorePhaseTwo() {

	for _, a_definition_4DB := range backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB {

		// next line of code is to avert unused variable compilation error
		_ = a_definition_4DB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		query := backRepoA_DEFINITION_4.db.Model(a_definition_4DB).Updates(*a_definition_4DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoA_DEFINITION_4.ResetReversePointers commits all staged instances of A_DEFINITION_4 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, a_definition_4 := range backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4Ptr {
		backRepoA_DEFINITION_4.ResetReversePointersInstance(backRepo, idx, a_definition_4)
	}

	return
}

func (backRepoA_DEFINITION_4 *BackRepoA_DEFINITION_4Struct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, a_definition_4 *models.A_DEFINITION_4) (Error error) {

	// fetch matching a_definition_4DB
	if a_definition_4DB, ok := backRepoA_DEFINITION_4.Map_A_DEFINITION_4DBID_A_DEFINITION_4DB[idx]; ok {
		_ = a_definition_4DB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoA_DEFINITION_4id_atBckpTime_newID map[uint]uint
