// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongxsd/test/reqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_A_DEFINITION_sql sql.NullBool
var dummy_A_DEFINITION_time time.Duration
var dummy_A_DEFINITION_sort sort.Float64Slice

// A_DEFINITIONAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model a_definitionAPI
type A_DEFINITIONAPI struct {
	gorm.Model

	models.A_DEFINITION_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	A_DEFINITIONPointersEncoding A_DEFINITIONPointersEncoding
}

// A_DEFINITIONPointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type A_DEFINITIONPointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// A_DEFINITIONDB describes a a_definition in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model a_definitionDB
type A_DEFINITIONDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field a_definitionDB.Name
	Name_Data sql.NullString

	// Declation for basic field a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF
	ATTRIBUTE_DEFINITION_INTEGER_REF_Data sql.NullString
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	A_DEFINITIONPointersEncoding
}

// A_DEFINITIONDBs arrays a_definitionDBs
// swagger:response a_definitionDBsResponse
type A_DEFINITIONDBs []A_DEFINITIONDB

// A_DEFINITIONDBResponse provides response
// swagger:response a_definitionDBResponse
type A_DEFINITIONDBResponse struct {
	A_DEFINITIONDB
}

// A_DEFINITIONWOP is a A_DEFINITION without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type A_DEFINITIONWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	ATTRIBUTE_DEFINITION_INTEGER_REF string `xlsx:"2"`
	// insertion for WOP pointer fields
}

var A_DEFINITION_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"ATTRIBUTE_DEFINITION_INTEGER_REF",
}

type BackRepoA_DEFINITIONStruct struct {
	// stores A_DEFINITIONDB according to their gorm ID
	Map_A_DEFINITIONDBID_A_DEFINITIONDB map[uint]*A_DEFINITIONDB

	// stores A_DEFINITIONDB ID according to A_DEFINITION address
	Map_A_DEFINITIONPtr_A_DEFINITIONDBID map[*models.A_DEFINITION]uint

	// stores A_DEFINITION according to their gorm ID
	Map_A_DEFINITIONDBID_A_DEFINITIONPtr map[uint]*models.A_DEFINITION

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) GetStage() (stage *models.StageStruct) {
	stage = backRepoA_DEFINITION.stage
	return
}

func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) GetDB() *gorm.DB {
	return backRepoA_DEFINITION.db
}

// GetA_DEFINITIONDBFromA_DEFINITIONPtr is a handy function to access the back repo instance from the stage instance
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) GetA_DEFINITIONDBFromA_DEFINITIONPtr(a_definition *models.A_DEFINITION) (a_definitionDB *A_DEFINITIONDB) {
	id := backRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition]
	a_definitionDB = backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[id]
	return
}

// BackRepoA_DEFINITION.CommitPhaseOne commits all staged instances of A_DEFINITION to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for a_definition := range stage.A_DEFINITIONs {
		backRepoA_DEFINITION.CommitPhaseOneInstance(a_definition)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, a_definition := range backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr {
		if _, ok := stage.A_DEFINITIONs[a_definition]; !ok {
			backRepoA_DEFINITION.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoA_DEFINITION.CommitDeleteInstance commits deletion of A_DEFINITION to the BackRepo
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CommitDeleteInstance(id uint) (Error error) {

	a_definition := backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr[id]

	// a_definition is not staged anymore, remove a_definitionDB
	a_definitionDB := backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[id]
	query := backRepoA_DEFINITION.db.Unscoped().Delete(&a_definitionDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID, a_definition)
	delete(backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr, id)
	delete(backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB, id)

	return
}

// BackRepoA_DEFINITION.CommitPhaseOneInstance commits a_definition staged instances of A_DEFINITION to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CommitPhaseOneInstance(a_definition *models.A_DEFINITION) (Error error) {

	// check if the a_definition is not commited yet
	if _, ok := backRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition]; ok {
		return
	}

	// initiate a_definition
	var a_definitionDB A_DEFINITIONDB
	a_definitionDB.CopyBasicFieldsFromA_DEFINITION(a_definition)

	query := backRepoA_DEFINITION.db.Create(&a_definitionDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition] = a_definitionDB.ID
	backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr[a_definitionDB.ID] = a_definition
	backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[a_definitionDB.ID] = &a_definitionDB

	return
}

// BackRepoA_DEFINITION.CommitPhaseTwo commits all staged instances of A_DEFINITION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, a_definition := range backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr {
		backRepoA_DEFINITION.CommitPhaseTwoInstance(backRepo, idx, a_definition)
	}

	return
}

// BackRepoA_DEFINITION.CommitPhaseTwoInstance commits {{structname }} of models.A_DEFINITION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, a_definition *models.A_DEFINITION) (Error error) {

	// fetch matching a_definitionDB
	if a_definitionDB, ok := backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[idx]; ok {

		a_definitionDB.CopyBasicFieldsFromA_DEFINITION(a_definition)

		// insertion point for translating pointers encodings into actual pointers
		query := backRepoA_DEFINITION.db.Save(&a_definitionDB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown A_DEFINITION intance %s", a_definition.Name))
		return err
	}

	return
}

// BackRepoA_DEFINITION.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CheckoutPhaseOne() (Error error) {

	a_definitionDBArray := make([]A_DEFINITIONDB, 0)
	query := backRepoA_DEFINITION.db.Find(&a_definitionDBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	a_definitionInstancesToBeRemovedFromTheStage := make(map[*models.A_DEFINITION]any)
	for key, value := range backRepoA_DEFINITION.stage.A_DEFINITIONs {
		a_definitionInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, a_definitionDB := range a_definitionDBArray {
		backRepoA_DEFINITION.CheckoutPhaseOneInstance(&a_definitionDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		a_definition, ok := backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr[a_definitionDB.ID]
		if ok {
			delete(a_definitionInstancesToBeRemovedFromTheStage, a_definition)
		}
	}

	// remove from stage and back repo's 3 maps all a_definitions that are not in the checkout
	for a_definition := range a_definitionInstancesToBeRemovedFromTheStage {
		a_definition.Unstage(backRepoA_DEFINITION.GetStage())

		// remove instance from the back repo 3 maps
		a_definitionID := backRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition]
		delete(backRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID, a_definition)
		delete(backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB, a_definitionID)
		delete(backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr, a_definitionID)
	}

	return
}

// CheckoutPhaseOneInstance takes a a_definitionDB that has been found in the DB, updates the backRepo and stages the
// models version of the a_definitionDB
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CheckoutPhaseOneInstance(a_definitionDB *A_DEFINITIONDB) (Error error) {

	a_definition, ok := backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr[a_definitionDB.ID]
	if !ok {
		a_definition = new(models.A_DEFINITION)

		backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr[a_definitionDB.ID] = a_definition
		backRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition] = a_definitionDB.ID

		// append model store with the new element
		a_definition.Name = a_definitionDB.Name_Data.String
		a_definition.Stage(backRepoA_DEFINITION.GetStage())
	}
	a_definitionDB.CopyBasicFieldsToA_DEFINITION(a_definition)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	a_definition.Stage(backRepoA_DEFINITION.GetStage())

	// preserve pointer to a_definitionDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_A_DEFINITIONDBID_A_DEFINITIONDB)[a_definitionDB hold variable pointers
	a_definitionDB_Data := *a_definitionDB
	preservedPtrToA_DEFINITION := &a_definitionDB_Data
	backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[a_definitionDB.ID] = preservedPtrToA_DEFINITION

	return
}

// BackRepoA_DEFINITION.CheckoutPhaseTwo Checkouts all staged instances of A_DEFINITION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, a_definitionDB := range backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB {
		backRepoA_DEFINITION.CheckoutPhaseTwoInstance(backRepo, a_definitionDB)
	}
	return
}

// BackRepoA_DEFINITION.CheckoutPhaseTwoInstance Checkouts staged instances of A_DEFINITION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, a_definitionDB *A_DEFINITIONDB) (Error error) {

	a_definition := backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr[a_definitionDB.ID]

	a_definitionDB.DecodePointers(backRepo, a_definition)

	return
}

func (a_definitionDB *A_DEFINITIONDB) DecodePointers(backRepo *BackRepoStruct, a_definition *models.A_DEFINITION) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitA_DEFINITION allows commit of a single a_definition (if already staged)
func (backRepo *BackRepoStruct) CommitA_DEFINITION(a_definition *models.A_DEFINITION) {
	backRepo.BackRepoA_DEFINITION.CommitPhaseOneInstance(a_definition)
	if id, ok := backRepo.BackRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition]; ok {
		backRepo.BackRepoA_DEFINITION.CommitPhaseTwoInstance(backRepo, id, a_definition)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitA_DEFINITION allows checkout of a single a_definition (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutA_DEFINITION(a_definition *models.A_DEFINITION) {
	// check if the a_definition is staged
	if _, ok := backRepo.BackRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition]; ok {

		if id, ok := backRepo.BackRepoA_DEFINITION.Map_A_DEFINITIONPtr_A_DEFINITIONDBID[a_definition]; ok {
			var a_definitionDB A_DEFINITIONDB
			a_definitionDB.ID = id

			if err := backRepo.BackRepoA_DEFINITION.db.First(&a_definitionDB, id).Error; err != nil {
				log.Fatalln("CheckoutA_DEFINITION : Problem with getting object with id:", id)
			}
			backRepo.BackRepoA_DEFINITION.CheckoutPhaseOneInstance(&a_definitionDB)
			backRepo.BackRepoA_DEFINITION.CheckoutPhaseTwoInstance(backRepo, &a_definitionDB)
		}
	}
}

// CopyBasicFieldsFromA_DEFINITION
func (a_definitionDB *A_DEFINITIONDB) CopyBasicFieldsFromA_DEFINITION(a_definition *models.A_DEFINITION) {
	// insertion point for fields commit

	a_definitionDB.Name_Data.String = a_definition.Name
	a_definitionDB.Name_Data.Valid = true

	a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.String = a_definition.ATTRIBUTE_DEFINITION_INTEGER_REF
	a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_DEFINITION_WOP
func (a_definitionDB *A_DEFINITIONDB) CopyBasicFieldsFromA_DEFINITION_WOP(a_definition *models.A_DEFINITION_WOP) {
	// insertion point for fields commit

	a_definitionDB.Name_Data.String = a_definition.Name
	a_definitionDB.Name_Data.Valid = true

	a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.String = a_definition.ATTRIBUTE_DEFINITION_INTEGER_REF
	a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_DEFINITIONWOP
func (a_definitionDB *A_DEFINITIONDB) CopyBasicFieldsFromA_DEFINITIONWOP(a_definition *A_DEFINITIONWOP) {
	// insertion point for fields commit

	a_definitionDB.Name_Data.String = a_definition.Name
	a_definitionDB.Name_Data.Valid = true

	a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.String = a_definition.ATTRIBUTE_DEFINITION_INTEGER_REF
	a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.Valid = true
}

// CopyBasicFieldsToA_DEFINITION
func (a_definitionDB *A_DEFINITIONDB) CopyBasicFieldsToA_DEFINITION(a_definition *models.A_DEFINITION) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_definition.Name = a_definitionDB.Name_Data.String
	a_definition.ATTRIBUTE_DEFINITION_INTEGER_REF = a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.String
}

// CopyBasicFieldsToA_DEFINITION_WOP
func (a_definitionDB *A_DEFINITIONDB) CopyBasicFieldsToA_DEFINITION_WOP(a_definition *models.A_DEFINITION_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_definition.Name = a_definitionDB.Name_Data.String
	a_definition.ATTRIBUTE_DEFINITION_INTEGER_REF = a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.String
}

// CopyBasicFieldsToA_DEFINITIONWOP
func (a_definitionDB *A_DEFINITIONDB) CopyBasicFieldsToA_DEFINITIONWOP(a_definition *A_DEFINITIONWOP) {
	a_definition.ID = int(a_definitionDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	a_definition.Name = a_definitionDB.Name_Data.String
	a_definition.ATTRIBUTE_DEFINITION_INTEGER_REF = a_definitionDB.ATTRIBUTE_DEFINITION_INTEGER_REF_Data.String
}

// Backup generates a json file from a slice of all A_DEFINITIONDB instances in the backrepo
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "A_DEFINITIONDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_DEFINITIONDB, 0)
	for _, a_definitionDB := range backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB {
		forBackup = append(forBackup, a_definitionDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json A_DEFINITION ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json A_DEFINITION file", err.Error())
	}
}

// Backup generates a json file from a slice of all A_DEFINITIONDB instances in the backrepo
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_DEFINITIONDB, 0)
	for _, a_definitionDB := range backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB {
		forBackup = append(forBackup, a_definitionDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("A_DEFINITION")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&A_DEFINITION_Fields, -1)
	for _, a_definitionDB := range forBackup {

		var a_definitionWOP A_DEFINITIONWOP
		a_definitionDB.CopyBasicFieldsToA_DEFINITIONWOP(&a_definitionWOP)

		row := sh.AddRow()
		row.WriteStruct(&a_definitionWOP, -1)
	}
}

// RestoreXL from the "A_DEFINITION" sheet all A_DEFINITIONDB instances
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoA_DEFINITIONid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["A_DEFINITION"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoA_DEFINITION.rowVisitorA_DEFINITION)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) rowVisitorA_DEFINITION(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var a_definitionWOP A_DEFINITIONWOP
		row.ReadStruct(&a_definitionWOP)

		// add the unmarshalled struct to the stage
		a_definitionDB := new(A_DEFINITIONDB)
		a_definitionDB.CopyBasicFieldsFromA_DEFINITIONWOP(&a_definitionWOP)

		a_definitionDB_ID_atBackupTime := a_definitionDB.ID
		a_definitionDB.ID = 0
		query := backRepoA_DEFINITION.db.Create(a_definitionDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[a_definitionDB.ID] = a_definitionDB
		BackRepoA_DEFINITIONid_atBckpTime_newID[a_definitionDB_ID_atBackupTime] = a_definitionDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "A_DEFINITIONDB.json" in dirPath that stores an array
// of A_DEFINITIONDB and stores it in the database
// the map BackRepoA_DEFINITIONid_atBckpTime_newID is updated accordingly
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoA_DEFINITIONid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "A_DEFINITIONDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json A_DEFINITION file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*A_DEFINITIONDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_A_DEFINITIONDBID_A_DEFINITIONDB
	for _, a_definitionDB := range forRestore {

		a_definitionDB_ID_atBackupTime := a_definitionDB.ID
		a_definitionDB.ID = 0
		query := backRepoA_DEFINITION.db.Create(a_definitionDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[a_definitionDB.ID] = a_definitionDB
		BackRepoA_DEFINITIONid_atBckpTime_newID[a_definitionDB_ID_atBackupTime] = a_definitionDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json A_DEFINITION file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<A_DEFINITION>id_atBckpTime_newID
// to compute new index
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) RestorePhaseTwo() {

	for _, a_definitionDB := range backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB {

		// next line of code is to avert unused variable compilation error
		_ = a_definitionDB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		query := backRepoA_DEFINITION.db.Model(a_definitionDB).Updates(*a_definitionDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoA_DEFINITION.ResetReversePointers commits all staged instances of A_DEFINITION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, a_definition := range backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONPtr {
		backRepoA_DEFINITION.ResetReversePointersInstance(backRepo, idx, a_definition)
	}

	return
}

func (backRepoA_DEFINITION *BackRepoA_DEFINITIONStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, a_definition *models.A_DEFINITION) (Error error) {

	// fetch matching a_definitionDB
	if a_definitionDB, ok := backRepoA_DEFINITION.Map_A_DEFINITIONDBID_A_DEFINITIONDB[idx]; ok {
		_ = a_definitionDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoA_DEFINITIONid_atBckpTime_newID map[uint]uint
