// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongxsd/test/reqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_A_SPEC_RELATIONS_1_sql sql.NullBool
var dummy_A_SPEC_RELATIONS_1_time time.Duration
var dummy_A_SPEC_RELATIONS_1_sort sort.Float64Slice

// A_SPEC_RELATIONS_1API is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model a_spec_relations_1API
type A_SPEC_RELATIONS_1API struct {
	gorm.Model

	models.A_SPEC_RELATIONS_1_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	A_SPEC_RELATIONS_1PointersEncoding A_SPEC_RELATIONS_1PointersEncoding
}

// A_SPEC_RELATIONS_1PointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type A_SPEC_RELATIONS_1PointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// A_SPEC_RELATIONS_1DB describes a a_spec_relations_1 in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model a_spec_relations_1DB
type A_SPEC_RELATIONS_1DB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field a_spec_relations_1DB.Name
	Name_Data sql.NullString

	// Declation for basic field a_spec_relations_1DB.SPEC_RELATION_REF
	SPEC_RELATION_REF_Data sql.NullString
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	A_SPEC_RELATIONS_1PointersEncoding
}

// A_SPEC_RELATIONS_1DBs arrays a_spec_relations_1DBs
// swagger:response a_spec_relations_1DBsResponse
type A_SPEC_RELATIONS_1DBs []A_SPEC_RELATIONS_1DB

// A_SPEC_RELATIONS_1DBResponse provides response
// swagger:response a_spec_relations_1DBResponse
type A_SPEC_RELATIONS_1DBResponse struct {
	A_SPEC_RELATIONS_1DB
}

// A_SPEC_RELATIONS_1WOP is a A_SPEC_RELATIONS_1 without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type A_SPEC_RELATIONS_1WOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	SPEC_RELATION_REF string `xlsx:"2"`
	// insertion for WOP pointer fields
}

var A_SPEC_RELATIONS_1_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"SPEC_RELATION_REF",
}

type BackRepoA_SPEC_RELATIONS_1Struct struct {
	// stores A_SPEC_RELATIONS_1DB according to their gorm ID
	Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB map[uint]*A_SPEC_RELATIONS_1DB

	// stores A_SPEC_RELATIONS_1DB ID according to A_SPEC_RELATIONS_1 address
	Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID map[*models.A_SPEC_RELATIONS_1]uint

	// stores A_SPEC_RELATIONS_1 according to their gorm ID
	Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr map[uint]*models.A_SPEC_RELATIONS_1

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) GetStage() (stage *models.StageStruct) {
	stage = backRepoA_SPEC_RELATIONS_1.stage
	return
}

func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) GetDB() *gorm.DB {
	return backRepoA_SPEC_RELATIONS_1.db
}

// GetA_SPEC_RELATIONS_1DBFromA_SPEC_RELATIONS_1Ptr is a handy function to access the back repo instance from the stage instance
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) GetA_SPEC_RELATIONS_1DBFromA_SPEC_RELATIONS_1Ptr(a_spec_relations_1 *models.A_SPEC_RELATIONS_1) (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) {
	id := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1]
	a_spec_relations_1DB = backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[id]
	return
}

// BackRepoA_SPEC_RELATIONS_1.CommitPhaseOne commits all staged instances of A_SPEC_RELATIONS_1 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for a_spec_relations_1 := range stage.A_SPEC_RELATIONS_1s {
		backRepoA_SPEC_RELATIONS_1.CommitPhaseOneInstance(a_spec_relations_1)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, a_spec_relations_1 := range backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr {
		if _, ok := stage.A_SPEC_RELATIONS_1s[a_spec_relations_1]; !ok {
			backRepoA_SPEC_RELATIONS_1.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoA_SPEC_RELATIONS_1.CommitDeleteInstance commits deletion of A_SPEC_RELATIONS_1 to the BackRepo
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CommitDeleteInstance(id uint) (Error error) {

	a_spec_relations_1 := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr[id]

	// a_spec_relations_1 is not staged anymore, remove a_spec_relations_1DB
	a_spec_relations_1DB := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[id]
	query := backRepoA_SPEC_RELATIONS_1.db.Unscoped().Delete(&a_spec_relations_1DB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID, a_spec_relations_1)
	delete(backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr, id)
	delete(backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB, id)

	return
}

// BackRepoA_SPEC_RELATIONS_1.CommitPhaseOneInstance commits a_spec_relations_1 staged instances of A_SPEC_RELATIONS_1 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CommitPhaseOneInstance(a_spec_relations_1 *models.A_SPEC_RELATIONS_1) (Error error) {

	// check if the a_spec_relations_1 is not commited yet
	if _, ok := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1]; ok {
		return
	}

	// initiate a_spec_relations_1
	var a_spec_relations_1DB A_SPEC_RELATIONS_1DB
	a_spec_relations_1DB.CopyBasicFieldsFromA_SPEC_RELATIONS_1(a_spec_relations_1)

	query := backRepoA_SPEC_RELATIONS_1.db.Create(&a_spec_relations_1DB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1] = a_spec_relations_1DB.ID
	backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr[a_spec_relations_1DB.ID] = a_spec_relations_1
	backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[a_spec_relations_1DB.ID] = &a_spec_relations_1DB

	return
}

// BackRepoA_SPEC_RELATIONS_1.CommitPhaseTwo commits all staged instances of A_SPEC_RELATIONS_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, a_spec_relations_1 := range backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr {
		backRepoA_SPEC_RELATIONS_1.CommitPhaseTwoInstance(backRepo, idx, a_spec_relations_1)
	}

	return
}

// BackRepoA_SPEC_RELATIONS_1.CommitPhaseTwoInstance commits {{structname }} of models.A_SPEC_RELATIONS_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, a_spec_relations_1 *models.A_SPEC_RELATIONS_1) (Error error) {

	// fetch matching a_spec_relations_1DB
	if a_spec_relations_1DB, ok := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[idx]; ok {

		a_spec_relations_1DB.CopyBasicFieldsFromA_SPEC_RELATIONS_1(a_spec_relations_1)

		// insertion point for translating pointers encodings into actual pointers
		query := backRepoA_SPEC_RELATIONS_1.db.Save(&a_spec_relations_1DB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown A_SPEC_RELATIONS_1 intance %s", a_spec_relations_1.Name))
		return err
	}

	return
}

// BackRepoA_SPEC_RELATIONS_1.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CheckoutPhaseOne() (Error error) {

	a_spec_relations_1DBArray := make([]A_SPEC_RELATIONS_1DB, 0)
	query := backRepoA_SPEC_RELATIONS_1.db.Find(&a_spec_relations_1DBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	a_spec_relations_1InstancesToBeRemovedFromTheStage := make(map[*models.A_SPEC_RELATIONS_1]any)
	for key, value := range backRepoA_SPEC_RELATIONS_1.stage.A_SPEC_RELATIONS_1s {
		a_spec_relations_1InstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, a_spec_relations_1DB := range a_spec_relations_1DBArray {
		backRepoA_SPEC_RELATIONS_1.CheckoutPhaseOneInstance(&a_spec_relations_1DB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		a_spec_relations_1, ok := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr[a_spec_relations_1DB.ID]
		if ok {
			delete(a_spec_relations_1InstancesToBeRemovedFromTheStage, a_spec_relations_1)
		}
	}

	// remove from stage and back repo's 3 maps all a_spec_relations_1s that are not in the checkout
	for a_spec_relations_1 := range a_spec_relations_1InstancesToBeRemovedFromTheStage {
		a_spec_relations_1.Unstage(backRepoA_SPEC_RELATIONS_1.GetStage())

		// remove instance from the back repo 3 maps
		a_spec_relations_1ID := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1]
		delete(backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID, a_spec_relations_1)
		delete(backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB, a_spec_relations_1ID)
		delete(backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr, a_spec_relations_1ID)
	}

	return
}

// CheckoutPhaseOneInstance takes a a_spec_relations_1DB that has been found in the DB, updates the backRepo and stages the
// models version of the a_spec_relations_1DB
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CheckoutPhaseOneInstance(a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) (Error error) {

	a_spec_relations_1, ok := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr[a_spec_relations_1DB.ID]
	if !ok {
		a_spec_relations_1 = new(models.A_SPEC_RELATIONS_1)

		backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr[a_spec_relations_1DB.ID] = a_spec_relations_1
		backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1] = a_spec_relations_1DB.ID

		// append model store with the new element
		a_spec_relations_1.Name = a_spec_relations_1DB.Name_Data.String
		a_spec_relations_1.Stage(backRepoA_SPEC_RELATIONS_1.GetStage())
	}
	a_spec_relations_1DB.CopyBasicFieldsToA_SPEC_RELATIONS_1(a_spec_relations_1)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	a_spec_relations_1.Stage(backRepoA_SPEC_RELATIONS_1.GetStage())

	// preserve pointer to a_spec_relations_1DB. Otherwise, pointer will is recycled and the map of pointers
	// Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB)[a_spec_relations_1DB hold variable pointers
	a_spec_relations_1DB_Data := *a_spec_relations_1DB
	preservedPtrToA_SPEC_RELATIONS_1 := &a_spec_relations_1DB_Data
	backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[a_spec_relations_1DB.ID] = preservedPtrToA_SPEC_RELATIONS_1

	return
}

// BackRepoA_SPEC_RELATIONS_1.CheckoutPhaseTwo Checkouts all staged instances of A_SPEC_RELATIONS_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, a_spec_relations_1DB := range backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB {
		backRepoA_SPEC_RELATIONS_1.CheckoutPhaseTwoInstance(backRepo, a_spec_relations_1DB)
	}
	return
}

// BackRepoA_SPEC_RELATIONS_1.CheckoutPhaseTwoInstance Checkouts staged instances of A_SPEC_RELATIONS_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) (Error error) {

	a_spec_relations_1 := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr[a_spec_relations_1DB.ID]

	a_spec_relations_1DB.DecodePointers(backRepo, a_spec_relations_1)

	return
}

func (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) DecodePointers(backRepo *BackRepoStruct, a_spec_relations_1 *models.A_SPEC_RELATIONS_1) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitA_SPEC_RELATIONS_1 allows commit of a single a_spec_relations_1 (if already staged)
func (backRepo *BackRepoStruct) CommitA_SPEC_RELATIONS_1(a_spec_relations_1 *models.A_SPEC_RELATIONS_1) {
	backRepo.BackRepoA_SPEC_RELATIONS_1.CommitPhaseOneInstance(a_spec_relations_1)
	if id, ok := backRepo.BackRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1]; ok {
		backRepo.BackRepoA_SPEC_RELATIONS_1.CommitPhaseTwoInstance(backRepo, id, a_spec_relations_1)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitA_SPEC_RELATIONS_1 allows checkout of a single a_spec_relations_1 (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutA_SPEC_RELATIONS_1(a_spec_relations_1 *models.A_SPEC_RELATIONS_1) {
	// check if the a_spec_relations_1 is staged
	if _, ok := backRepo.BackRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1]; ok {

		if id, ok := backRepo.BackRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1Ptr_A_SPEC_RELATIONS_1DBID[a_spec_relations_1]; ok {
			var a_spec_relations_1DB A_SPEC_RELATIONS_1DB
			a_spec_relations_1DB.ID = id

			if err := backRepo.BackRepoA_SPEC_RELATIONS_1.db.First(&a_spec_relations_1DB, id).Error; err != nil {
				log.Fatalln("CheckoutA_SPEC_RELATIONS_1 : Problem with getting object with id:", id)
			}
			backRepo.BackRepoA_SPEC_RELATIONS_1.CheckoutPhaseOneInstance(&a_spec_relations_1DB)
			backRepo.BackRepoA_SPEC_RELATIONS_1.CheckoutPhaseTwoInstance(backRepo, &a_spec_relations_1DB)
		}
	}
}

// CopyBasicFieldsFromA_SPEC_RELATIONS_1
func (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) CopyBasicFieldsFromA_SPEC_RELATIONS_1(a_spec_relations_1 *models.A_SPEC_RELATIONS_1) {
	// insertion point for fields commit

	a_spec_relations_1DB.Name_Data.String = a_spec_relations_1.Name
	a_spec_relations_1DB.Name_Data.Valid = true

	a_spec_relations_1DB.SPEC_RELATION_REF_Data.String = a_spec_relations_1.SPEC_RELATION_REF
	a_spec_relations_1DB.SPEC_RELATION_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_SPEC_RELATIONS_1_WOP
func (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) CopyBasicFieldsFromA_SPEC_RELATIONS_1_WOP(a_spec_relations_1 *models.A_SPEC_RELATIONS_1_WOP) {
	// insertion point for fields commit

	a_spec_relations_1DB.Name_Data.String = a_spec_relations_1.Name
	a_spec_relations_1DB.Name_Data.Valid = true

	a_spec_relations_1DB.SPEC_RELATION_REF_Data.String = a_spec_relations_1.SPEC_RELATION_REF
	a_spec_relations_1DB.SPEC_RELATION_REF_Data.Valid = true
}

// CopyBasicFieldsFromA_SPEC_RELATIONS_1WOP
func (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) CopyBasicFieldsFromA_SPEC_RELATIONS_1WOP(a_spec_relations_1 *A_SPEC_RELATIONS_1WOP) {
	// insertion point for fields commit

	a_spec_relations_1DB.Name_Data.String = a_spec_relations_1.Name
	a_spec_relations_1DB.Name_Data.Valid = true

	a_spec_relations_1DB.SPEC_RELATION_REF_Data.String = a_spec_relations_1.SPEC_RELATION_REF
	a_spec_relations_1DB.SPEC_RELATION_REF_Data.Valid = true
}

// CopyBasicFieldsToA_SPEC_RELATIONS_1
func (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) CopyBasicFieldsToA_SPEC_RELATIONS_1(a_spec_relations_1 *models.A_SPEC_RELATIONS_1) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_spec_relations_1.Name = a_spec_relations_1DB.Name_Data.String
	a_spec_relations_1.SPEC_RELATION_REF = a_spec_relations_1DB.SPEC_RELATION_REF_Data.String
}

// CopyBasicFieldsToA_SPEC_RELATIONS_1_WOP
func (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) CopyBasicFieldsToA_SPEC_RELATIONS_1_WOP(a_spec_relations_1 *models.A_SPEC_RELATIONS_1_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	a_spec_relations_1.Name = a_spec_relations_1DB.Name_Data.String
	a_spec_relations_1.SPEC_RELATION_REF = a_spec_relations_1DB.SPEC_RELATION_REF_Data.String
}

// CopyBasicFieldsToA_SPEC_RELATIONS_1WOP
func (a_spec_relations_1DB *A_SPEC_RELATIONS_1DB) CopyBasicFieldsToA_SPEC_RELATIONS_1WOP(a_spec_relations_1 *A_SPEC_RELATIONS_1WOP) {
	a_spec_relations_1.ID = int(a_spec_relations_1DB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	a_spec_relations_1.Name = a_spec_relations_1DB.Name_Data.String
	a_spec_relations_1.SPEC_RELATION_REF = a_spec_relations_1DB.SPEC_RELATION_REF_Data.String
}

// Backup generates a json file from a slice of all A_SPEC_RELATIONS_1DB instances in the backrepo
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "A_SPEC_RELATIONS_1DB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_SPEC_RELATIONS_1DB, 0)
	for _, a_spec_relations_1DB := range backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB {
		forBackup = append(forBackup, a_spec_relations_1DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json A_SPEC_RELATIONS_1 ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json A_SPEC_RELATIONS_1 file", err.Error())
	}
}

// Backup generates a json file from a slice of all A_SPEC_RELATIONS_1DB instances in the backrepo
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*A_SPEC_RELATIONS_1DB, 0)
	for _, a_spec_relations_1DB := range backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB {
		forBackup = append(forBackup, a_spec_relations_1DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("A_SPEC_RELATIONS_1")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&A_SPEC_RELATIONS_1_Fields, -1)
	for _, a_spec_relations_1DB := range forBackup {

		var a_spec_relations_1WOP A_SPEC_RELATIONS_1WOP
		a_spec_relations_1DB.CopyBasicFieldsToA_SPEC_RELATIONS_1WOP(&a_spec_relations_1WOP)

		row := sh.AddRow()
		row.WriteStruct(&a_spec_relations_1WOP, -1)
	}
}

// RestoreXL from the "A_SPEC_RELATIONS_1" sheet all A_SPEC_RELATIONS_1DB instances
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoA_SPEC_RELATIONS_1id_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["A_SPEC_RELATIONS_1"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoA_SPEC_RELATIONS_1.rowVisitorA_SPEC_RELATIONS_1)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) rowVisitorA_SPEC_RELATIONS_1(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var a_spec_relations_1WOP A_SPEC_RELATIONS_1WOP
		row.ReadStruct(&a_spec_relations_1WOP)

		// add the unmarshalled struct to the stage
		a_spec_relations_1DB := new(A_SPEC_RELATIONS_1DB)
		a_spec_relations_1DB.CopyBasicFieldsFromA_SPEC_RELATIONS_1WOP(&a_spec_relations_1WOP)

		a_spec_relations_1DB_ID_atBackupTime := a_spec_relations_1DB.ID
		a_spec_relations_1DB.ID = 0
		query := backRepoA_SPEC_RELATIONS_1.db.Create(a_spec_relations_1DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[a_spec_relations_1DB.ID] = a_spec_relations_1DB
		BackRepoA_SPEC_RELATIONS_1id_atBckpTime_newID[a_spec_relations_1DB_ID_atBackupTime] = a_spec_relations_1DB.ID
	}
	return nil
}

// RestorePhaseOne read the file "A_SPEC_RELATIONS_1DB.json" in dirPath that stores an array
// of A_SPEC_RELATIONS_1DB and stores it in the database
// the map BackRepoA_SPEC_RELATIONS_1id_atBckpTime_newID is updated accordingly
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoA_SPEC_RELATIONS_1id_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "A_SPEC_RELATIONS_1DB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json A_SPEC_RELATIONS_1 file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*A_SPEC_RELATIONS_1DB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB
	for _, a_spec_relations_1DB := range forRestore {

		a_spec_relations_1DB_ID_atBackupTime := a_spec_relations_1DB.ID
		a_spec_relations_1DB.ID = 0
		query := backRepoA_SPEC_RELATIONS_1.db.Create(a_spec_relations_1DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[a_spec_relations_1DB.ID] = a_spec_relations_1DB
		BackRepoA_SPEC_RELATIONS_1id_atBckpTime_newID[a_spec_relations_1DB_ID_atBackupTime] = a_spec_relations_1DB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json A_SPEC_RELATIONS_1 file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<A_SPEC_RELATIONS_1>id_atBckpTime_newID
// to compute new index
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) RestorePhaseTwo() {

	for _, a_spec_relations_1DB := range backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB {

		// next line of code is to avert unused variable compilation error
		_ = a_spec_relations_1DB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		query := backRepoA_SPEC_RELATIONS_1.db.Model(a_spec_relations_1DB).Updates(*a_spec_relations_1DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoA_SPEC_RELATIONS_1.ResetReversePointers commits all staged instances of A_SPEC_RELATIONS_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, a_spec_relations_1 := range backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1Ptr {
		backRepoA_SPEC_RELATIONS_1.ResetReversePointersInstance(backRepo, idx, a_spec_relations_1)
	}

	return
}

func (backRepoA_SPEC_RELATIONS_1 *BackRepoA_SPEC_RELATIONS_1Struct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, a_spec_relations_1 *models.A_SPEC_RELATIONS_1) (Error error) {

	// fetch matching a_spec_relations_1DB
	if a_spec_relations_1DB, ok := backRepoA_SPEC_RELATIONS_1.Map_A_SPEC_RELATIONS_1DBID_A_SPEC_RELATIONS_1DB[idx]; ok {
		_ = a_spec_relations_1DB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoA_SPEC_RELATIONS_1id_atBckpTime_newID map[uint]uint
