// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongxsd/test/reqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_ATTRIBUTE_DEFINITION_ENUMERATION_sql sql.NullBool
var dummy_ATTRIBUTE_DEFINITION_ENUMERATION_time time.Duration
var dummy_ATTRIBUTE_DEFINITION_ENUMERATION_sort sort.Float64Slice

// ATTRIBUTE_DEFINITION_ENUMERATIONAPI is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model attribute_definition_enumerationAPI
type ATTRIBUTE_DEFINITION_ENUMERATIONAPI struct {
	gorm.Model

	models.ATTRIBUTE_DEFINITION_ENUMERATION_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	ATTRIBUTE_DEFINITION_ENUMERATIONPointersEncoding ATTRIBUTE_DEFINITION_ENUMERATIONPointersEncoding
}

// ATTRIBUTE_DEFINITION_ENUMERATIONPointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type ATTRIBUTE_DEFINITION_ENUMERATIONPointersEncoding struct {
	// insertion for pointer fields encoding declaration

	// field ALTERNATIVE_ID is a pointer to another Struct (optional or 0..1)
	// This field is generated into another field to enable AS ONE association
	ALTERNATIVE_IDID sql.NullInt64

	// field DEFAULT_VALUE is a pointer to another Struct (optional or 0..1)
	// This field is generated into another field to enable AS ONE association
	DEFAULT_VALUEID sql.NullInt64

	// field TYPE is a pointer to another Struct (optional or 0..1)
	// This field is generated into another field to enable AS ONE association
	TYPEID sql.NullInt64
}

// ATTRIBUTE_DEFINITION_ENUMERATIONDB describes a attribute_definition_enumeration in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model attribute_definition_enumerationDB
type ATTRIBUTE_DEFINITION_ENUMERATIONDB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field attribute_definition_enumerationDB.Name
	Name_Data sql.NullString

	// Declation for basic field attribute_definition_enumerationDB.DESC
	DESC_Data sql.NullString

	// Declation for basic field attribute_definition_enumerationDB.IDENTIFIER
	IDENTIFIER_Data sql.NullString

	// Declation for basic field attribute_definition_enumerationDB.IS_EDITABLE
	// provide the sql storage for the boolan
	IS_EDITABLE_Data sql.NullBool

	// Declation for basic field attribute_definition_enumerationDB.LAST_CHANGE
	LAST_CHANGE_Data sql.NullString

	// Declation for basic field attribute_definition_enumerationDB.LONG_NAME
	LONG_NAME_Data sql.NullString

	// Declation for basic field attribute_definition_enumerationDB.MULTI_VALUED
	// provide the sql storage for the boolan
	MULTI_VALUED_Data sql.NullBool
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	ATTRIBUTE_DEFINITION_ENUMERATIONPointersEncoding
}

// ATTRIBUTE_DEFINITION_ENUMERATIONDBs arrays attribute_definition_enumerationDBs
// swagger:response attribute_definition_enumerationDBsResponse
type ATTRIBUTE_DEFINITION_ENUMERATIONDBs []ATTRIBUTE_DEFINITION_ENUMERATIONDB

// ATTRIBUTE_DEFINITION_ENUMERATIONDBResponse provides response
// swagger:response attribute_definition_enumerationDBResponse
type ATTRIBUTE_DEFINITION_ENUMERATIONDBResponse struct {
	ATTRIBUTE_DEFINITION_ENUMERATIONDB
}

// ATTRIBUTE_DEFINITION_ENUMERATIONWOP is a ATTRIBUTE_DEFINITION_ENUMERATION without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type ATTRIBUTE_DEFINITION_ENUMERATIONWOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	DESC string `xlsx:"2"`

	IDENTIFIER string `xlsx:"3"`

	IS_EDITABLE bool `xlsx:"4"`

	LAST_CHANGE string `xlsx:"5"`

	LONG_NAME string `xlsx:"6"`

	MULTI_VALUED bool `xlsx:"7"`
	// insertion for WOP pointer fields
}

var ATTRIBUTE_DEFINITION_ENUMERATION_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"DESC",
	"IDENTIFIER",
	"IS_EDITABLE",
	"LAST_CHANGE",
	"LONG_NAME",
	"MULTI_VALUED",
}

type BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct struct {
	// stores ATTRIBUTE_DEFINITION_ENUMERATIONDB according to their gorm ID
	Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB map[uint]*ATTRIBUTE_DEFINITION_ENUMERATIONDB

	// stores ATTRIBUTE_DEFINITION_ENUMERATIONDB ID according to ATTRIBUTE_DEFINITION_ENUMERATION address
	Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID map[*models.ATTRIBUTE_DEFINITION_ENUMERATION]uint

	// stores ATTRIBUTE_DEFINITION_ENUMERATION according to their gorm ID
	Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr map[uint]*models.ATTRIBUTE_DEFINITION_ENUMERATION

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) GetStage() (stage *models.StageStruct) {
	stage = backRepoATTRIBUTE_DEFINITION_ENUMERATION.stage
	return
}

func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) GetDB() *gorm.DB {
	return backRepoATTRIBUTE_DEFINITION_ENUMERATION.db
}

// GetATTRIBUTE_DEFINITION_ENUMERATIONDBFromATTRIBUTE_DEFINITION_ENUMERATIONPtr is a handy function to access the back repo instance from the stage instance
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) GetATTRIBUTE_DEFINITION_ENUMERATIONDBFromATTRIBUTE_DEFINITION_ENUMERATIONPtr(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) {
	id := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration]
	attribute_definition_enumerationDB = backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[id]
	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseOne commits all staged instances of ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for attribute_definition_enumeration := range stage.ATTRIBUTE_DEFINITION_ENUMERATIONs {
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseOneInstance(attribute_definition_enumeration)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, attribute_definition_enumeration := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr {
		if _, ok := stage.ATTRIBUTE_DEFINITION_ENUMERATIONs[attribute_definition_enumeration]; !ok {
			backRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitDeleteInstance commits deletion of ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CommitDeleteInstance(id uint) (Error error) {

	attribute_definition_enumeration := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr[id]

	// attribute_definition_enumeration is not staged anymore, remove attribute_definition_enumerationDB
	attribute_definition_enumerationDB := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[id]
	query := backRepoATTRIBUTE_DEFINITION_ENUMERATION.db.Unscoped().Delete(&attribute_definition_enumerationDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID, attribute_definition_enumeration)
	delete(backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr, id)
	delete(backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB, id)

	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseOneInstance commits attribute_definition_enumeration staged instances of ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CommitPhaseOneInstance(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) (Error error) {

	// check if the attribute_definition_enumeration is not commited yet
	if _, ok := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration]; ok {
		return
	}

	// initiate attribute_definition_enumeration
	var attribute_definition_enumerationDB ATTRIBUTE_DEFINITION_ENUMERATIONDB
	attribute_definition_enumerationDB.CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATION(attribute_definition_enumeration)

	query := backRepoATTRIBUTE_DEFINITION_ENUMERATION.db.Create(&attribute_definition_enumerationDB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration] = attribute_definition_enumerationDB.ID
	backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr[attribute_definition_enumerationDB.ID] = attribute_definition_enumeration
	backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[attribute_definition_enumerationDB.ID] = &attribute_definition_enumerationDB

	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseTwo commits all staged instances of ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, attribute_definition_enumeration := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr {
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseTwoInstance(backRepo, idx, attribute_definition_enumeration)
	}

	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseTwoInstance commits {{structname }} of models.ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) (Error error) {

	// fetch matching attribute_definition_enumerationDB
	if attribute_definition_enumerationDB, ok := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[idx]; ok {

		attribute_definition_enumerationDB.CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATION(attribute_definition_enumeration)

		// insertion point for translating pointers encodings into actual pointers
		// commit pointer value attribute_definition_enumeration.ALTERNATIVE_ID translates to updating the attribute_definition_enumeration.ALTERNATIVE_IDID
		attribute_definition_enumerationDB.ALTERNATIVE_IDID.Valid = true // allow for a 0 value (nil association)
		if attribute_definition_enumeration.ALTERNATIVE_ID != nil {
			if ALTERNATIVE_IDId, ok := backRepo.BackRepoA_ALTERNATIVE_ID.Map_A_ALTERNATIVE_IDPtr_A_ALTERNATIVE_IDDBID[attribute_definition_enumeration.ALTERNATIVE_ID]; ok {
				attribute_definition_enumerationDB.ALTERNATIVE_IDID.Int64 = int64(ALTERNATIVE_IDId)
				attribute_definition_enumerationDB.ALTERNATIVE_IDID.Valid = true
			}
		} else {
			attribute_definition_enumerationDB.ALTERNATIVE_IDID.Int64 = 0
			attribute_definition_enumerationDB.ALTERNATIVE_IDID.Valid = true
		}

		// commit pointer value attribute_definition_enumeration.DEFAULT_VALUE translates to updating the attribute_definition_enumeration.DEFAULT_VALUEID
		attribute_definition_enumerationDB.DEFAULT_VALUEID.Valid = true // allow for a 0 value (nil association)
		if attribute_definition_enumeration.DEFAULT_VALUE != nil {
			if DEFAULT_VALUEId, ok := backRepo.BackRepoA_ATTRIBUTE_VALUE_ENUMERATION.Map_A_ATTRIBUTE_VALUE_ENUMERATIONPtr_A_ATTRIBUTE_VALUE_ENUMERATIONDBID[attribute_definition_enumeration.DEFAULT_VALUE]; ok {
				attribute_definition_enumerationDB.DEFAULT_VALUEID.Int64 = int64(DEFAULT_VALUEId)
				attribute_definition_enumerationDB.DEFAULT_VALUEID.Valid = true
			}
		} else {
			attribute_definition_enumerationDB.DEFAULT_VALUEID.Int64 = 0
			attribute_definition_enumerationDB.DEFAULT_VALUEID.Valid = true
		}

		// commit pointer value attribute_definition_enumeration.TYPE translates to updating the attribute_definition_enumeration.TYPEID
		attribute_definition_enumerationDB.TYPEID.Valid = true // allow for a 0 value (nil association)
		if attribute_definition_enumeration.TYPE != nil {
			if TYPEId, ok := backRepo.BackRepoA_DATATYPE_DEFINITION_ENUMERATION_REF.Map_A_DATATYPE_DEFINITION_ENUMERATION_REFPtr_A_DATATYPE_DEFINITION_ENUMERATION_REFDBID[attribute_definition_enumeration.TYPE]; ok {
				attribute_definition_enumerationDB.TYPEID.Int64 = int64(TYPEId)
				attribute_definition_enumerationDB.TYPEID.Valid = true
			}
		} else {
			attribute_definition_enumerationDB.TYPEID.Int64 = 0
			attribute_definition_enumerationDB.TYPEID.Valid = true
		}

		query := backRepoATTRIBUTE_DEFINITION_ENUMERATION.db.Save(&attribute_definition_enumerationDB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown ATTRIBUTE_DEFINITION_ENUMERATION intance %s", attribute_definition_enumeration.Name))
		return err
	}

	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CheckoutPhaseOne() (Error error) {

	attribute_definition_enumerationDBArray := make([]ATTRIBUTE_DEFINITION_ENUMERATIONDB, 0)
	query := backRepoATTRIBUTE_DEFINITION_ENUMERATION.db.Find(&attribute_definition_enumerationDBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	attribute_definition_enumerationInstancesToBeRemovedFromTheStage := make(map[*models.ATTRIBUTE_DEFINITION_ENUMERATION]any)
	for key, value := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.stage.ATTRIBUTE_DEFINITION_ENUMERATIONs {
		attribute_definition_enumerationInstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, attribute_definition_enumerationDB := range attribute_definition_enumerationDBArray {
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.CheckoutPhaseOneInstance(&attribute_definition_enumerationDB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		attribute_definition_enumeration, ok := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr[attribute_definition_enumerationDB.ID]
		if ok {
			delete(attribute_definition_enumerationInstancesToBeRemovedFromTheStage, attribute_definition_enumeration)
		}
	}

	// remove from stage and back repo's 3 maps all attribute_definition_enumerations that are not in the checkout
	for attribute_definition_enumeration := range attribute_definition_enumerationInstancesToBeRemovedFromTheStage {
		attribute_definition_enumeration.Unstage(backRepoATTRIBUTE_DEFINITION_ENUMERATION.GetStage())

		// remove instance from the back repo 3 maps
		attribute_definition_enumerationID := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration]
		delete(backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID, attribute_definition_enumeration)
		delete(backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB, attribute_definition_enumerationID)
		delete(backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr, attribute_definition_enumerationID)
	}

	return
}

// CheckoutPhaseOneInstance takes a attribute_definition_enumerationDB that has been found in the DB, updates the backRepo and stages the
// models version of the attribute_definition_enumerationDB
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CheckoutPhaseOneInstance(attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) (Error error) {

	attribute_definition_enumeration, ok := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr[attribute_definition_enumerationDB.ID]
	if !ok {
		attribute_definition_enumeration = new(models.ATTRIBUTE_DEFINITION_ENUMERATION)

		backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr[attribute_definition_enumerationDB.ID] = attribute_definition_enumeration
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration] = attribute_definition_enumerationDB.ID

		// append model store with the new element
		attribute_definition_enumeration.Name = attribute_definition_enumerationDB.Name_Data.String
		attribute_definition_enumeration.Stage(backRepoATTRIBUTE_DEFINITION_ENUMERATION.GetStage())
	}
	attribute_definition_enumerationDB.CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATION(attribute_definition_enumeration)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	attribute_definition_enumeration.Stage(backRepoATTRIBUTE_DEFINITION_ENUMERATION.GetStage())

	// preserve pointer to attribute_definition_enumerationDB. Otherwise, pointer will is recycled and the map of pointers
	// Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB)[attribute_definition_enumerationDB hold variable pointers
	attribute_definition_enumerationDB_Data := *attribute_definition_enumerationDB
	preservedPtrToATTRIBUTE_DEFINITION_ENUMERATION := &attribute_definition_enumerationDB_Data
	backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[attribute_definition_enumerationDB.ID] = preservedPtrToATTRIBUTE_DEFINITION_ENUMERATION

	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CheckoutPhaseTwo Checkouts all staged instances of ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, attribute_definition_enumerationDB := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB {
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.CheckoutPhaseTwoInstance(backRepo, attribute_definition_enumerationDB)
	}
	return
}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CheckoutPhaseTwoInstance Checkouts staged instances of ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) (Error error) {

	attribute_definition_enumeration := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr[attribute_definition_enumerationDB.ID]

	attribute_definition_enumerationDB.DecodePointers(backRepo, attribute_definition_enumeration)

	return
}

func (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) DecodePointers(backRepo *BackRepoStruct, attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) {

	// insertion point for checkout of pointer encoding
	// ALTERNATIVE_ID field
	attribute_definition_enumeration.ALTERNATIVE_ID = nil
	if attribute_definition_enumerationDB.ALTERNATIVE_IDID.Int64 != 0 {
		attribute_definition_enumeration.ALTERNATIVE_ID = backRepo.BackRepoA_ALTERNATIVE_ID.Map_A_ALTERNATIVE_IDDBID_A_ALTERNATIVE_IDPtr[uint(attribute_definition_enumerationDB.ALTERNATIVE_IDID.Int64)]
	}
	// DEFAULT_VALUE field
	attribute_definition_enumeration.DEFAULT_VALUE = nil
	if attribute_definition_enumerationDB.DEFAULT_VALUEID.Int64 != 0 {
		attribute_definition_enumeration.DEFAULT_VALUE = backRepo.BackRepoA_ATTRIBUTE_VALUE_ENUMERATION.Map_A_ATTRIBUTE_VALUE_ENUMERATIONDBID_A_ATTRIBUTE_VALUE_ENUMERATIONPtr[uint(attribute_definition_enumerationDB.DEFAULT_VALUEID.Int64)]
	}
	// TYPE field
	attribute_definition_enumeration.TYPE = nil
	if attribute_definition_enumerationDB.TYPEID.Int64 != 0 {
		attribute_definition_enumeration.TYPE = backRepo.BackRepoA_DATATYPE_DEFINITION_ENUMERATION_REF.Map_A_DATATYPE_DEFINITION_ENUMERATION_REFDBID_A_DATATYPE_DEFINITION_ENUMERATION_REFPtr[uint(attribute_definition_enumerationDB.TYPEID.Int64)]
	}
	return
}

// CommitATTRIBUTE_DEFINITION_ENUMERATION allows commit of a single attribute_definition_enumeration (if already staged)
func (backRepo *BackRepoStruct) CommitATTRIBUTE_DEFINITION_ENUMERATION(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) {
	backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseOneInstance(attribute_definition_enumeration)
	if id, ok := backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration]; ok {
		backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CommitPhaseTwoInstance(backRepo, id, attribute_definition_enumeration)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitATTRIBUTE_DEFINITION_ENUMERATION allows checkout of a single attribute_definition_enumeration (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutATTRIBUTE_DEFINITION_ENUMERATION(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) {
	// check if the attribute_definition_enumeration is staged
	if _, ok := backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration]; ok {

		if id, ok := backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONPtr_ATTRIBUTE_DEFINITION_ENUMERATIONDBID[attribute_definition_enumeration]; ok {
			var attribute_definition_enumerationDB ATTRIBUTE_DEFINITION_ENUMERATIONDB
			attribute_definition_enumerationDB.ID = id

			if err := backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.db.First(&attribute_definition_enumerationDB, id).Error; err != nil {
				log.Fatalln("CheckoutATTRIBUTE_DEFINITION_ENUMERATION : Problem with getting object with id:", id)
			}
			backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CheckoutPhaseOneInstance(&attribute_definition_enumerationDB)
			backRepo.BackRepoATTRIBUTE_DEFINITION_ENUMERATION.CheckoutPhaseTwoInstance(backRepo, &attribute_definition_enumerationDB)
		}
	}
}

// CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATION
func (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATION(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) {
	// insertion point for fields commit

	attribute_definition_enumerationDB.Name_Data.String = attribute_definition_enumeration.Name
	attribute_definition_enumerationDB.Name_Data.Valid = true

	attribute_definition_enumerationDB.DESC_Data.String = attribute_definition_enumeration.DESC
	attribute_definition_enumerationDB.DESC_Data.Valid = true

	attribute_definition_enumerationDB.IDENTIFIER_Data.String = attribute_definition_enumeration.IDENTIFIER
	attribute_definition_enumerationDB.IDENTIFIER_Data.Valid = true

	attribute_definition_enumerationDB.IS_EDITABLE_Data.Bool = attribute_definition_enumeration.IS_EDITABLE
	attribute_definition_enumerationDB.IS_EDITABLE_Data.Valid = true

	attribute_definition_enumerationDB.LAST_CHANGE_Data.String = attribute_definition_enumeration.LAST_CHANGE
	attribute_definition_enumerationDB.LAST_CHANGE_Data.Valid = true

	attribute_definition_enumerationDB.LONG_NAME_Data.String = attribute_definition_enumeration.LONG_NAME
	attribute_definition_enumerationDB.LONG_NAME_Data.Valid = true

	attribute_definition_enumerationDB.MULTI_VALUED_Data.Bool = attribute_definition_enumeration.MULTI_VALUED
	attribute_definition_enumerationDB.MULTI_VALUED_Data.Valid = true
}

// CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATION_WOP
func (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATION_WOP(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION_WOP) {
	// insertion point for fields commit

	attribute_definition_enumerationDB.Name_Data.String = attribute_definition_enumeration.Name
	attribute_definition_enumerationDB.Name_Data.Valid = true

	attribute_definition_enumerationDB.DESC_Data.String = attribute_definition_enumeration.DESC
	attribute_definition_enumerationDB.DESC_Data.Valid = true

	attribute_definition_enumerationDB.IDENTIFIER_Data.String = attribute_definition_enumeration.IDENTIFIER
	attribute_definition_enumerationDB.IDENTIFIER_Data.Valid = true

	attribute_definition_enumerationDB.IS_EDITABLE_Data.Bool = attribute_definition_enumeration.IS_EDITABLE
	attribute_definition_enumerationDB.IS_EDITABLE_Data.Valid = true

	attribute_definition_enumerationDB.LAST_CHANGE_Data.String = attribute_definition_enumeration.LAST_CHANGE
	attribute_definition_enumerationDB.LAST_CHANGE_Data.Valid = true

	attribute_definition_enumerationDB.LONG_NAME_Data.String = attribute_definition_enumeration.LONG_NAME
	attribute_definition_enumerationDB.LONG_NAME_Data.Valid = true

	attribute_definition_enumerationDB.MULTI_VALUED_Data.Bool = attribute_definition_enumeration.MULTI_VALUED
	attribute_definition_enumerationDB.MULTI_VALUED_Data.Valid = true
}

// CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATIONWOP
func (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATIONWOP(attribute_definition_enumeration *ATTRIBUTE_DEFINITION_ENUMERATIONWOP) {
	// insertion point for fields commit

	attribute_definition_enumerationDB.Name_Data.String = attribute_definition_enumeration.Name
	attribute_definition_enumerationDB.Name_Data.Valid = true

	attribute_definition_enumerationDB.DESC_Data.String = attribute_definition_enumeration.DESC
	attribute_definition_enumerationDB.DESC_Data.Valid = true

	attribute_definition_enumerationDB.IDENTIFIER_Data.String = attribute_definition_enumeration.IDENTIFIER
	attribute_definition_enumerationDB.IDENTIFIER_Data.Valid = true

	attribute_definition_enumerationDB.IS_EDITABLE_Data.Bool = attribute_definition_enumeration.IS_EDITABLE
	attribute_definition_enumerationDB.IS_EDITABLE_Data.Valid = true

	attribute_definition_enumerationDB.LAST_CHANGE_Data.String = attribute_definition_enumeration.LAST_CHANGE
	attribute_definition_enumerationDB.LAST_CHANGE_Data.Valid = true

	attribute_definition_enumerationDB.LONG_NAME_Data.String = attribute_definition_enumeration.LONG_NAME
	attribute_definition_enumerationDB.LONG_NAME_Data.Valid = true

	attribute_definition_enumerationDB.MULTI_VALUED_Data.Bool = attribute_definition_enumeration.MULTI_VALUED
	attribute_definition_enumerationDB.MULTI_VALUED_Data.Valid = true
}

// CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATION
func (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATION(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) {
	// insertion point for checkout of basic fields (back repo to stage)
	attribute_definition_enumeration.Name = attribute_definition_enumerationDB.Name_Data.String
	attribute_definition_enumeration.DESC = attribute_definition_enumerationDB.DESC_Data.String
	attribute_definition_enumeration.IDENTIFIER = attribute_definition_enumerationDB.IDENTIFIER_Data.String
	attribute_definition_enumeration.IS_EDITABLE = attribute_definition_enumerationDB.IS_EDITABLE_Data.Bool
	attribute_definition_enumeration.LAST_CHANGE = attribute_definition_enumerationDB.LAST_CHANGE_Data.String
	attribute_definition_enumeration.LONG_NAME = attribute_definition_enumerationDB.LONG_NAME_Data.String
	attribute_definition_enumeration.MULTI_VALUED = attribute_definition_enumerationDB.MULTI_VALUED_Data.Bool
}

// CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATION_WOP
func (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATION_WOP(attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	attribute_definition_enumeration.Name = attribute_definition_enumerationDB.Name_Data.String
	attribute_definition_enumeration.DESC = attribute_definition_enumerationDB.DESC_Data.String
	attribute_definition_enumeration.IDENTIFIER = attribute_definition_enumerationDB.IDENTIFIER_Data.String
	attribute_definition_enumeration.IS_EDITABLE = attribute_definition_enumerationDB.IS_EDITABLE_Data.Bool
	attribute_definition_enumeration.LAST_CHANGE = attribute_definition_enumerationDB.LAST_CHANGE_Data.String
	attribute_definition_enumeration.LONG_NAME = attribute_definition_enumerationDB.LONG_NAME_Data.String
	attribute_definition_enumeration.MULTI_VALUED = attribute_definition_enumerationDB.MULTI_VALUED_Data.Bool
}

// CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATIONWOP
func (attribute_definition_enumerationDB *ATTRIBUTE_DEFINITION_ENUMERATIONDB) CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATIONWOP(attribute_definition_enumeration *ATTRIBUTE_DEFINITION_ENUMERATIONWOP) {
	attribute_definition_enumeration.ID = int(attribute_definition_enumerationDB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	attribute_definition_enumeration.Name = attribute_definition_enumerationDB.Name_Data.String
	attribute_definition_enumeration.DESC = attribute_definition_enumerationDB.DESC_Data.String
	attribute_definition_enumeration.IDENTIFIER = attribute_definition_enumerationDB.IDENTIFIER_Data.String
	attribute_definition_enumeration.IS_EDITABLE = attribute_definition_enumerationDB.IS_EDITABLE_Data.Bool
	attribute_definition_enumeration.LAST_CHANGE = attribute_definition_enumerationDB.LAST_CHANGE_Data.String
	attribute_definition_enumeration.LONG_NAME = attribute_definition_enumerationDB.LONG_NAME_Data.String
	attribute_definition_enumeration.MULTI_VALUED = attribute_definition_enumerationDB.MULTI_VALUED_Data.Bool
}

// Backup generates a json file from a slice of all ATTRIBUTE_DEFINITION_ENUMERATIONDB instances in the backrepo
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "ATTRIBUTE_DEFINITION_ENUMERATIONDB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*ATTRIBUTE_DEFINITION_ENUMERATIONDB, 0)
	for _, attribute_definition_enumerationDB := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB {
		forBackup = append(forBackup, attribute_definition_enumerationDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json ATTRIBUTE_DEFINITION_ENUMERATION ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json ATTRIBUTE_DEFINITION_ENUMERATION file", err.Error())
	}
}

// Backup generates a json file from a slice of all ATTRIBUTE_DEFINITION_ENUMERATIONDB instances in the backrepo
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*ATTRIBUTE_DEFINITION_ENUMERATIONDB, 0)
	for _, attribute_definition_enumerationDB := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB {
		forBackup = append(forBackup, attribute_definition_enumerationDB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("ATTRIBUTE_DEFINITION_ENUMERATION")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&ATTRIBUTE_DEFINITION_ENUMERATION_Fields, -1)
	for _, attribute_definition_enumerationDB := range forBackup {

		var attribute_definition_enumerationWOP ATTRIBUTE_DEFINITION_ENUMERATIONWOP
		attribute_definition_enumerationDB.CopyBasicFieldsToATTRIBUTE_DEFINITION_ENUMERATIONWOP(&attribute_definition_enumerationWOP)

		row := sh.AddRow()
		row.WriteStruct(&attribute_definition_enumerationWOP, -1)
	}
}

// RestoreXL from the "ATTRIBUTE_DEFINITION_ENUMERATION" sheet all ATTRIBUTE_DEFINITION_ENUMERATIONDB instances
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoATTRIBUTE_DEFINITION_ENUMERATIONid_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["ATTRIBUTE_DEFINITION_ENUMERATION"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoATTRIBUTE_DEFINITION_ENUMERATION.rowVisitorATTRIBUTE_DEFINITION_ENUMERATION)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) rowVisitorATTRIBUTE_DEFINITION_ENUMERATION(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var attribute_definition_enumerationWOP ATTRIBUTE_DEFINITION_ENUMERATIONWOP
		row.ReadStruct(&attribute_definition_enumerationWOP)

		// add the unmarshalled struct to the stage
		attribute_definition_enumerationDB := new(ATTRIBUTE_DEFINITION_ENUMERATIONDB)
		attribute_definition_enumerationDB.CopyBasicFieldsFromATTRIBUTE_DEFINITION_ENUMERATIONWOP(&attribute_definition_enumerationWOP)

		attribute_definition_enumerationDB_ID_atBackupTime := attribute_definition_enumerationDB.ID
		attribute_definition_enumerationDB.ID = 0
		query := backRepoATTRIBUTE_DEFINITION_ENUMERATION.db.Create(attribute_definition_enumerationDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[attribute_definition_enumerationDB.ID] = attribute_definition_enumerationDB
		BackRepoATTRIBUTE_DEFINITION_ENUMERATIONid_atBckpTime_newID[attribute_definition_enumerationDB_ID_atBackupTime] = attribute_definition_enumerationDB.ID
	}
	return nil
}

// RestorePhaseOne read the file "ATTRIBUTE_DEFINITION_ENUMERATIONDB.json" in dirPath that stores an array
// of ATTRIBUTE_DEFINITION_ENUMERATIONDB and stores it in the database
// the map BackRepoATTRIBUTE_DEFINITION_ENUMERATIONid_atBckpTime_newID is updated accordingly
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoATTRIBUTE_DEFINITION_ENUMERATIONid_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "ATTRIBUTE_DEFINITION_ENUMERATIONDB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json ATTRIBUTE_DEFINITION_ENUMERATION file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*ATTRIBUTE_DEFINITION_ENUMERATIONDB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB
	for _, attribute_definition_enumerationDB := range forRestore {

		attribute_definition_enumerationDB_ID_atBackupTime := attribute_definition_enumerationDB.ID
		attribute_definition_enumerationDB.ID = 0
		query := backRepoATTRIBUTE_DEFINITION_ENUMERATION.db.Create(attribute_definition_enumerationDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[attribute_definition_enumerationDB.ID] = attribute_definition_enumerationDB
		BackRepoATTRIBUTE_DEFINITION_ENUMERATIONid_atBckpTime_newID[attribute_definition_enumerationDB_ID_atBackupTime] = attribute_definition_enumerationDB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json ATTRIBUTE_DEFINITION_ENUMERATION file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<ATTRIBUTE_DEFINITION_ENUMERATION>id_atBckpTime_newID
// to compute new index
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) RestorePhaseTwo() {

	for _, attribute_definition_enumerationDB := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB {

		// next line of code is to avert unused variable compilation error
		_ = attribute_definition_enumerationDB

		// insertion point for reindexing pointers encoding
		// reindexing ALTERNATIVE_ID field
		if attribute_definition_enumerationDB.ALTERNATIVE_IDID.Int64 != 0 {
			attribute_definition_enumerationDB.ALTERNATIVE_IDID.Int64 = int64(BackRepoA_ALTERNATIVE_IDid_atBckpTime_newID[uint(attribute_definition_enumerationDB.ALTERNATIVE_IDID.Int64)])
			attribute_definition_enumerationDB.ALTERNATIVE_IDID.Valid = true
		}

		// reindexing DEFAULT_VALUE field
		if attribute_definition_enumerationDB.DEFAULT_VALUEID.Int64 != 0 {
			attribute_definition_enumerationDB.DEFAULT_VALUEID.Int64 = int64(BackRepoA_ATTRIBUTE_VALUE_ENUMERATIONid_atBckpTime_newID[uint(attribute_definition_enumerationDB.DEFAULT_VALUEID.Int64)])
			attribute_definition_enumerationDB.DEFAULT_VALUEID.Valid = true
		}

		// reindexing TYPE field
		if attribute_definition_enumerationDB.TYPEID.Int64 != 0 {
			attribute_definition_enumerationDB.TYPEID.Int64 = int64(BackRepoA_DATATYPE_DEFINITION_ENUMERATION_REFid_atBckpTime_newID[uint(attribute_definition_enumerationDB.TYPEID.Int64)])
			attribute_definition_enumerationDB.TYPEID.Valid = true
		}

		// update databse with new index encoding
		query := backRepoATTRIBUTE_DEFINITION_ENUMERATION.db.Model(attribute_definition_enumerationDB).Updates(*attribute_definition_enumerationDB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoATTRIBUTE_DEFINITION_ENUMERATION.ResetReversePointers commits all staged instances of ATTRIBUTE_DEFINITION_ENUMERATION to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, attribute_definition_enumeration := range backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONPtr {
		backRepoATTRIBUTE_DEFINITION_ENUMERATION.ResetReversePointersInstance(backRepo, idx, attribute_definition_enumeration)
	}

	return
}

func (backRepoATTRIBUTE_DEFINITION_ENUMERATION *BackRepoATTRIBUTE_DEFINITION_ENUMERATIONStruct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, attribute_definition_enumeration *models.ATTRIBUTE_DEFINITION_ENUMERATION) (Error error) {

	// fetch matching attribute_definition_enumerationDB
	if attribute_definition_enumerationDB, ok := backRepoATTRIBUTE_DEFINITION_ENUMERATION.Map_ATTRIBUTE_DEFINITION_ENUMERATIONDBID_ATTRIBUTE_DEFINITION_ENUMERATIONDB[idx]; ok {
		_ = attribute_definition_enumerationDB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoATTRIBUTE_DEFINITION_ENUMERATIONid_atBckpTime_newID map[uint]uint
