// generated by stacks/gong/go/models/orm_file_per_struct_back_repo.go
package orm

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gorm.io/gorm"

	"github.com/tealeg/xlsx/v3"

	"github.com/fullstack-lang/gongxsd/test/reqif/go/models"
)

// dummy variable to have the import declaration wihthout compile failure (even if no code needing this import is generated)
var dummy_Renamed_RELATION_GROUP_TYPE_REF_1_sql sql.NullBool
var dummy_Renamed_RELATION_GROUP_TYPE_REF_1_time time.Duration
var dummy_Renamed_RELATION_GROUP_TYPE_REF_1_sort sort.Float64Slice

// Renamed_RELATION_GROUP_TYPE_REF_1API is the input in POST API
//
// for POST, API, one needs the fields of the model as well as the fields
// from associations ("Has One" and "Has Many") that are generated to
// fullfill the ORM requirements for associations
//
// swagger:model renamed_relation_group_type_ref_1API
type Renamed_RELATION_GROUP_TYPE_REF_1API struct {
	gorm.Model

	models.Renamed_RELATION_GROUP_TYPE_REF_1_WOP

	// encoding of pointers
	// for API, it cannot be embedded
	Renamed_RELATION_GROUP_TYPE_REF_1PointersEncoding Renamed_RELATION_GROUP_TYPE_REF_1PointersEncoding
}

// Renamed_RELATION_GROUP_TYPE_REF_1PointersEncoding encodes pointers to Struct and
// reverse pointers of slice of poitners to Struct
type Renamed_RELATION_GROUP_TYPE_REF_1PointersEncoding struct {
	// insertion for pointer fields encoding declaration
}

// Renamed_RELATION_GROUP_TYPE_REF_1DB describes a renamed_relation_group_type_ref_1 in the database
//
// It incorporates the GORM ID, basic fields from the model (because they can be serialized),
// the encoded version of pointers
//
// swagger:model renamed_relation_group_type_ref_1DB
type Renamed_RELATION_GROUP_TYPE_REF_1DB struct {
	gorm.Model

	// insertion for basic fields declaration

	// Declation for basic field renamed_relation_group_type_ref_1DB.Name
	Name_Data sql.NullString

	// Declation for basic field renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF
	RELATION_GROUP_TYPE_REF_Data sql.NullString
	
	// encoding of pointers
	// for GORM serialization, it is necessary to embed to Pointer Encoding declaration
	Renamed_RELATION_GROUP_TYPE_REF_1PointersEncoding
}

// Renamed_RELATION_GROUP_TYPE_REF_1DBs arrays renamed_relation_group_type_ref_1DBs
// swagger:response renamed_relation_group_type_ref_1DBsResponse
type Renamed_RELATION_GROUP_TYPE_REF_1DBs []Renamed_RELATION_GROUP_TYPE_REF_1DB

// Renamed_RELATION_GROUP_TYPE_REF_1DBResponse provides response
// swagger:response renamed_relation_group_type_ref_1DBResponse
type Renamed_RELATION_GROUP_TYPE_REF_1DBResponse struct {
	Renamed_RELATION_GROUP_TYPE_REF_1DB
}

// Renamed_RELATION_GROUP_TYPE_REF_1WOP is a Renamed_RELATION_GROUP_TYPE_REF_1 without pointers (WOP is an acronym for "Without Pointers")
// it holds the same basic fields but pointers are encoded into uint
type Renamed_RELATION_GROUP_TYPE_REF_1WOP struct {
	ID int `xlsx:"0"`

	// insertion for WOP basic fields

	Name string `xlsx:"1"`

	RELATION_GROUP_TYPE_REF string `xlsx:"2"`
	// insertion for WOP pointer fields
}

var Renamed_RELATION_GROUP_TYPE_REF_1_Fields = []string{
	// insertion for WOP basic fields
	"ID",
	"Name",
	"RELATION_GROUP_TYPE_REF",
}

type BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct struct {
	// stores Renamed_RELATION_GROUP_TYPE_REF_1DB according to their gorm ID
	Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB map[uint]*Renamed_RELATION_GROUP_TYPE_REF_1DB

	// stores Renamed_RELATION_GROUP_TYPE_REF_1DB ID according to Renamed_RELATION_GROUP_TYPE_REF_1 address
	Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID map[*models.Renamed_RELATION_GROUP_TYPE_REF_1]uint

	// stores Renamed_RELATION_GROUP_TYPE_REF_1 according to their gorm ID
	Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr map[uint]*models.Renamed_RELATION_GROUP_TYPE_REF_1

	db *gorm.DB

	stage *models.StageStruct
}

func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) GetStage() (stage *models.StageStruct) {
	stage = backRepoRenamed_RELATION_GROUP_TYPE_REF_1.stage
	return
}

func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) GetDB() *gorm.DB {
	return backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db
}

// GetRenamed_RELATION_GROUP_TYPE_REF_1DBFromRenamed_RELATION_GROUP_TYPE_REF_1Ptr is a handy function to access the back repo instance from the stage instance
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) GetRenamed_RELATION_GROUP_TYPE_REF_1DBFromRenamed_RELATION_GROUP_TYPE_REF_1Ptr(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) {
	id := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1]
	renamed_relation_group_type_ref_1DB = backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[id]
	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseOne commits all staged instances of Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CommitPhaseOne(stage *models.StageStruct) (Error error) {

	for renamed_relation_group_type_ref_1 := range stage.Renamed_RELATION_GROUP_TYPE_REF_1s {
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseOneInstance(renamed_relation_group_type_ref_1)
	}

	// parse all backRepo instance and checks wether some instance have been unstaged
	// in this case, remove them from the back repo
	for id, renamed_relation_group_type_ref_1 := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr {
		if _, ok := stage.Renamed_RELATION_GROUP_TYPE_REF_1s[renamed_relation_group_type_ref_1]; !ok {
			backRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitDeleteInstance(id)
		}
	}

	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitDeleteInstance commits deletion of Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CommitDeleteInstance(id uint) (Error error) {

	renamed_relation_group_type_ref_1 := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr[id]

	// renamed_relation_group_type_ref_1 is not staged anymore, remove renamed_relation_group_type_ref_1DB
	renamed_relation_group_type_ref_1DB := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[id]
	query := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.Unscoped().Delete(&renamed_relation_group_type_ref_1DB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	delete(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID, renamed_relation_group_type_ref_1)
	delete(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr, id)
	delete(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB, id)

	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseOneInstance commits renamed_relation_group_type_ref_1 staged instances of Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
// Phase One is the creation of instance in the database if it is not yet done to get the unique ID for each staged instance
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CommitPhaseOneInstance(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) (Error error) {

	// check if the renamed_relation_group_type_ref_1 is not commited yet
	if _, ok := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1]; ok {
		return
	}

	// initiate renamed_relation_group_type_ref_1
	var renamed_relation_group_type_ref_1DB Renamed_RELATION_GROUP_TYPE_REF_1DB
	renamed_relation_group_type_ref_1DB.CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1(renamed_relation_group_type_ref_1)

	query := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.Create(&renamed_relation_group_type_ref_1DB)
	if query.Error != nil {
		log.Fatal(query.Error)
	}

	// update stores
	backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1] = renamed_relation_group_type_ref_1DB.ID
	backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr[renamed_relation_group_type_ref_1DB.ID] = renamed_relation_group_type_ref_1
	backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[renamed_relation_group_type_ref_1DB.ID] = &renamed_relation_group_type_ref_1DB

	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseTwo commits all staged instances of Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CommitPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	for idx, renamed_relation_group_type_ref_1 := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr {
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseTwoInstance(backRepo, idx, renamed_relation_group_type_ref_1)
	}

	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseTwoInstance commits {{structname }} of models.Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CommitPhaseTwoInstance(backRepo *BackRepoStruct, idx uint, renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) (Error error) {

	// fetch matching renamed_relation_group_type_ref_1DB
	if renamed_relation_group_type_ref_1DB, ok := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[idx]; ok {

		renamed_relation_group_type_ref_1DB.CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1(renamed_relation_group_type_ref_1)

		// insertion point for translating pointers encodings into actual pointers
		query := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.Save(&renamed_relation_group_type_ref_1DB)
		if query.Error != nil {
			log.Fatalln(query.Error)
		}

	} else {
		err := errors.New(
			fmt.Sprintf("Unkown Renamed_RELATION_GROUP_TYPE_REF_1 intance %s", renamed_relation_group_type_ref_1.Name))
		return err
	}

	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CheckoutPhaseOne Checkouts all BackRepo instances to the Stage
//
// Phase One will result in having instances on the stage aligned with the back repo
// pointers are not initialized yet (this is for phase two)
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CheckoutPhaseOne() (Error error) {

	renamed_relation_group_type_ref_1DBArray := make([]Renamed_RELATION_GROUP_TYPE_REF_1DB, 0)
	query := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.Find(&renamed_relation_group_type_ref_1DBArray)
	if query.Error != nil {
		return query.Error
	}

	// list of instances to be removed
	// start from the initial map on the stage and remove instances that have been checked out
	renamed_relation_group_type_ref_1InstancesToBeRemovedFromTheStage := make(map[*models.Renamed_RELATION_GROUP_TYPE_REF_1]any)
	for key, value := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.stage.Renamed_RELATION_GROUP_TYPE_REF_1s {
		renamed_relation_group_type_ref_1InstancesToBeRemovedFromTheStage[key] = value
	}

	// copy orm objects to the the map
	for _, renamed_relation_group_type_ref_1DB := range renamed_relation_group_type_ref_1DBArray {
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.CheckoutPhaseOneInstance(&renamed_relation_group_type_ref_1DB)

		// do not remove this instance from the stage, therefore
		// remove instance from the list of instances to be be removed from the stage
		renamed_relation_group_type_ref_1, ok := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr[renamed_relation_group_type_ref_1DB.ID]
		if ok {
			delete(renamed_relation_group_type_ref_1InstancesToBeRemovedFromTheStage, renamed_relation_group_type_ref_1)
		}
	}

	// remove from stage and back repo's 3 maps all renamed_relation_group_type_ref_1s that are not in the checkout
	for renamed_relation_group_type_ref_1 := range renamed_relation_group_type_ref_1InstancesToBeRemovedFromTheStage {
		renamed_relation_group_type_ref_1.Unstage(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.GetStage())

		// remove instance from the back repo 3 maps
		renamed_relation_group_type_ref_1ID := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1]
		delete(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID, renamed_relation_group_type_ref_1)
		delete(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB, renamed_relation_group_type_ref_1ID)
		delete(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr, renamed_relation_group_type_ref_1ID)
	}

	return
}

// CheckoutPhaseOneInstance takes a renamed_relation_group_type_ref_1DB that has been found in the DB, updates the backRepo and stages the
// models version of the renamed_relation_group_type_ref_1DB
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CheckoutPhaseOneInstance(renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) (Error error) {

	renamed_relation_group_type_ref_1, ok := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr[renamed_relation_group_type_ref_1DB.ID]
	if !ok {
		renamed_relation_group_type_ref_1 = new(models.Renamed_RELATION_GROUP_TYPE_REF_1)

		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr[renamed_relation_group_type_ref_1DB.ID] = renamed_relation_group_type_ref_1
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1] = renamed_relation_group_type_ref_1DB.ID

		// append model store with the new element
		renamed_relation_group_type_ref_1.Name = renamed_relation_group_type_ref_1DB.Name_Data.String
		renamed_relation_group_type_ref_1.Stage(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.GetStage())
	}
	renamed_relation_group_type_ref_1DB.CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1(renamed_relation_group_type_ref_1)

	// in some cases, the instance might have been unstaged. It is necessary to stage it again
	renamed_relation_group_type_ref_1.Stage(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.GetStage())

	// preserve pointer to renamed_relation_group_type_ref_1DB. Otherwise, pointer will is recycled and the map of pointers
	// Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB)[renamed_relation_group_type_ref_1DB hold variable pointers
	renamed_relation_group_type_ref_1DB_Data := *renamed_relation_group_type_ref_1DB
	preservedPtrToRenamed_RELATION_GROUP_TYPE_REF_1 := &renamed_relation_group_type_ref_1DB_Data
	backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[renamed_relation_group_type_ref_1DB.ID] = preservedPtrToRenamed_RELATION_GROUP_TYPE_REF_1

	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CheckoutPhaseTwo Checkouts all staged instances of Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CheckoutPhaseTwo(backRepo *BackRepoStruct) (Error error) {

	// parse all DB instance and update all pointer fields of the translated models instance
	for _, renamed_relation_group_type_ref_1DB := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB {
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.CheckoutPhaseTwoInstance(backRepo, renamed_relation_group_type_ref_1DB)
	}
	return
}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CheckoutPhaseTwoInstance Checkouts staged instances of Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) CheckoutPhaseTwoInstance(backRepo *BackRepoStruct, renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) (Error error) {

	renamed_relation_group_type_ref_1 := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr[renamed_relation_group_type_ref_1DB.ID]

	renamed_relation_group_type_ref_1DB.DecodePointers(backRepo, renamed_relation_group_type_ref_1)

	return
}

func (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) DecodePointers(backRepo *BackRepoStruct, renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) {

	// insertion point for checkout of pointer encoding
	return
}

// CommitRenamed_RELATION_GROUP_TYPE_REF_1 allows commit of a single renamed_relation_group_type_ref_1 (if already staged)
func (backRepo *BackRepoStruct) CommitRenamed_RELATION_GROUP_TYPE_REF_1(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) {
	backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseOneInstance(renamed_relation_group_type_ref_1)
	if id, ok := backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1]; ok {
		backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CommitPhaseTwoInstance(backRepo, id, renamed_relation_group_type_ref_1)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
}

// CommitRenamed_RELATION_GROUP_TYPE_REF_1 allows checkout of a single renamed_relation_group_type_ref_1 (if already staged and with a BackRepo id)
func (backRepo *BackRepoStruct) CheckoutRenamed_RELATION_GROUP_TYPE_REF_1(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) {
	// check if the renamed_relation_group_type_ref_1 is staged
	if _, ok := backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1]; ok {

		if id, ok := backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1Ptr_Renamed_RELATION_GROUP_TYPE_REF_1DBID[renamed_relation_group_type_ref_1]; ok {
			var renamed_relation_group_type_ref_1DB Renamed_RELATION_GROUP_TYPE_REF_1DB
			renamed_relation_group_type_ref_1DB.ID = id

			if err := backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.First(&renamed_relation_group_type_ref_1DB, id).Error; err != nil {
				log.Fatalln("CheckoutRenamed_RELATION_GROUP_TYPE_REF_1 : Problem with getting object with id:", id)
			}
			backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CheckoutPhaseOneInstance(&renamed_relation_group_type_ref_1DB)
			backRepo.BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.CheckoutPhaseTwoInstance(backRepo, &renamed_relation_group_type_ref_1DB)
		}
	}
}

// CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1
func (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) {
	// insertion point for fields commit

	renamed_relation_group_type_ref_1DB.Name_Data.String = renamed_relation_group_type_ref_1.Name
	renamed_relation_group_type_ref_1DB.Name_Data.Valid = true

	renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.String = renamed_relation_group_type_ref_1.RELATION_GROUP_TYPE_REF
	renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.Valid = true
}

// CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1_WOP
func (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1_WOP(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1_WOP) {
	// insertion point for fields commit

	renamed_relation_group_type_ref_1DB.Name_Data.String = renamed_relation_group_type_ref_1.Name
	renamed_relation_group_type_ref_1DB.Name_Data.Valid = true

	renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.String = renamed_relation_group_type_ref_1.RELATION_GROUP_TYPE_REF
	renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.Valid = true
}

// CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1WOP
func (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1WOP(renamed_relation_group_type_ref_1 *Renamed_RELATION_GROUP_TYPE_REF_1WOP) {
	// insertion point for fields commit

	renamed_relation_group_type_ref_1DB.Name_Data.String = renamed_relation_group_type_ref_1.Name
	renamed_relation_group_type_ref_1DB.Name_Data.Valid = true

	renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.String = renamed_relation_group_type_ref_1.RELATION_GROUP_TYPE_REF
	renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.Valid = true
}

// CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1
func (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) {
	// insertion point for checkout of basic fields (back repo to stage)
	renamed_relation_group_type_ref_1.Name = renamed_relation_group_type_ref_1DB.Name_Data.String
	renamed_relation_group_type_ref_1.RELATION_GROUP_TYPE_REF = renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.String
}

// CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1_WOP
func (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1_WOP(renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1_WOP) {
	// insertion point for checkout of basic fields (back repo to stage)
	renamed_relation_group_type_ref_1.Name = renamed_relation_group_type_ref_1DB.Name_Data.String
	renamed_relation_group_type_ref_1.RELATION_GROUP_TYPE_REF = renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.String
}

// CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1WOP
func (renamed_relation_group_type_ref_1DB *Renamed_RELATION_GROUP_TYPE_REF_1DB) CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1WOP(renamed_relation_group_type_ref_1 *Renamed_RELATION_GROUP_TYPE_REF_1WOP) {
	renamed_relation_group_type_ref_1.ID = int(renamed_relation_group_type_ref_1DB.ID)
	// insertion point for checkout of basic fields (back repo to stage)
	renamed_relation_group_type_ref_1.Name = renamed_relation_group_type_ref_1DB.Name_Data.String
	renamed_relation_group_type_ref_1.RELATION_GROUP_TYPE_REF = renamed_relation_group_type_ref_1DB.RELATION_GROUP_TYPE_REF_Data.String
}

// Backup generates a json file from a slice of all Renamed_RELATION_GROUP_TYPE_REF_1DB instances in the backrepo
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) Backup(dirPath string) {

	filename := filepath.Join(dirPath, "Renamed_RELATION_GROUP_TYPE_REF_1DB.json")

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Renamed_RELATION_GROUP_TYPE_REF_1DB, 0)
	for _, renamed_relation_group_type_ref_1DB := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB {
		forBackup = append(forBackup, renamed_relation_group_type_ref_1DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	file, err := json.MarshalIndent(forBackup, "", " ")

	if err != nil {
		log.Fatal("Cannot json Renamed_RELATION_GROUP_TYPE_REF_1 ", filename, " ", err.Error())
	}

	err = ioutil.WriteFile(filename, file, 0644)
	if err != nil {
		log.Fatal("Cannot write the json Renamed_RELATION_GROUP_TYPE_REF_1 file", err.Error())
	}
}

// Backup generates a json file from a slice of all Renamed_RELATION_GROUP_TYPE_REF_1DB instances in the backrepo
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) BackupXL(file *xlsx.File) {

	// organize the map into an array with increasing IDs, in order to have repoductible
	// backup file
	forBackup := make([]*Renamed_RELATION_GROUP_TYPE_REF_1DB, 0)
	for _, renamed_relation_group_type_ref_1DB := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB {
		forBackup = append(forBackup, renamed_relation_group_type_ref_1DB)
	}

	sort.Slice(forBackup[:], func(i, j int) bool {
		return forBackup[i].ID < forBackup[j].ID
	})

	sh, err := file.AddSheet("Renamed_RELATION_GROUP_TYPE_REF_1")
	if err != nil {
		log.Fatal("Cannot add XL file", err.Error())
	}
	_ = sh

	row := sh.AddRow()
	row.WriteSlice(&Renamed_RELATION_GROUP_TYPE_REF_1_Fields, -1)
	for _, renamed_relation_group_type_ref_1DB := range forBackup {

		var renamed_relation_group_type_ref_1WOP Renamed_RELATION_GROUP_TYPE_REF_1WOP
		renamed_relation_group_type_ref_1DB.CopyBasicFieldsToRenamed_RELATION_GROUP_TYPE_REF_1WOP(&renamed_relation_group_type_ref_1WOP)

		row := sh.AddRow()
		row.WriteStruct(&renamed_relation_group_type_ref_1WOP, -1)
	}
}

// RestoreXL from the "Renamed_RELATION_GROUP_TYPE_REF_1" sheet all Renamed_RELATION_GROUP_TYPE_REF_1DB instances
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) RestoreXLPhaseOne(file *xlsx.File) {

	// resets the map
	BackRepoRenamed_RELATION_GROUP_TYPE_REF_1id_atBckpTime_newID = make(map[uint]uint)

	sh, ok := file.Sheet["Renamed_RELATION_GROUP_TYPE_REF_1"]
	_ = sh
	if !ok {
		log.Fatal(errors.New("sheet not found"))
	}

	// log.Println("Max row is", sh.MaxRow)
	err := sh.ForEachRow(backRepoRenamed_RELATION_GROUP_TYPE_REF_1.rowVisitorRenamed_RELATION_GROUP_TYPE_REF_1)
	if err != nil {
		log.Fatal("Err=", err)
	}
}

func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) rowVisitorRenamed_RELATION_GROUP_TYPE_REF_1(row *xlsx.Row) error {

	log.Printf("row line %d\n", row.GetCoordinate())
	log.Println(row)

	// skip first line
	if row.GetCoordinate() > 0 {
		var renamed_relation_group_type_ref_1WOP Renamed_RELATION_GROUP_TYPE_REF_1WOP
		row.ReadStruct(&renamed_relation_group_type_ref_1WOP)

		// add the unmarshalled struct to the stage
		renamed_relation_group_type_ref_1DB := new(Renamed_RELATION_GROUP_TYPE_REF_1DB)
		renamed_relation_group_type_ref_1DB.CopyBasicFieldsFromRenamed_RELATION_GROUP_TYPE_REF_1WOP(&renamed_relation_group_type_ref_1WOP)

		renamed_relation_group_type_ref_1DB_ID_atBackupTime := renamed_relation_group_type_ref_1DB.ID
		renamed_relation_group_type_ref_1DB.ID = 0
		query := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.Create(renamed_relation_group_type_ref_1DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[renamed_relation_group_type_ref_1DB.ID] = renamed_relation_group_type_ref_1DB
		BackRepoRenamed_RELATION_GROUP_TYPE_REF_1id_atBckpTime_newID[renamed_relation_group_type_ref_1DB_ID_atBackupTime] = renamed_relation_group_type_ref_1DB.ID
	}
	return nil
}

// RestorePhaseOne read the file "Renamed_RELATION_GROUP_TYPE_REF_1DB.json" in dirPath that stores an array
// of Renamed_RELATION_GROUP_TYPE_REF_1DB and stores it in the database
// the map BackRepoRenamed_RELATION_GROUP_TYPE_REF_1id_atBckpTime_newID is updated accordingly
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) RestorePhaseOne(dirPath string) {

	// resets the map
	BackRepoRenamed_RELATION_GROUP_TYPE_REF_1id_atBckpTime_newID = make(map[uint]uint)

	filename := filepath.Join(dirPath, "Renamed_RELATION_GROUP_TYPE_REF_1DB.json")
	jsonFile, err := os.Open(filename)
	// if we os.Open returns an error then handle it
	if err != nil {
		log.Fatal("Cannot restore/open the json Renamed_RELATION_GROUP_TYPE_REF_1 file", filename, " ", err.Error())
	}

	// read our opened jsonFile as a byte array.
	byteValue, _ := ioutil.ReadAll(jsonFile)

	var forRestore []*Renamed_RELATION_GROUP_TYPE_REF_1DB

	err = json.Unmarshal(byteValue, &forRestore)

	// fill up Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB
	for _, renamed_relation_group_type_ref_1DB := range forRestore {

		renamed_relation_group_type_ref_1DB_ID_atBackupTime := renamed_relation_group_type_ref_1DB.ID
		renamed_relation_group_type_ref_1DB.ID = 0
		query := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.Create(renamed_relation_group_type_ref_1DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[renamed_relation_group_type_ref_1DB.ID] = renamed_relation_group_type_ref_1DB
		BackRepoRenamed_RELATION_GROUP_TYPE_REF_1id_atBckpTime_newID[renamed_relation_group_type_ref_1DB_ID_atBackupTime] = renamed_relation_group_type_ref_1DB.ID
	}

	if err != nil {
		log.Fatal("Cannot restore/unmarshall json Renamed_RELATION_GROUP_TYPE_REF_1 file", err.Error())
	}
}

// RestorePhaseTwo uses all map BackRepo<Renamed_RELATION_GROUP_TYPE_REF_1>id_atBckpTime_newID
// to compute new index
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) RestorePhaseTwo() {

	for _, renamed_relation_group_type_ref_1DB := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB {

		// next line of code is to avert unused variable compilation error
		_ = renamed_relation_group_type_ref_1DB

		// insertion point for reindexing pointers encoding
		// update databse with new index encoding
		query := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.db.Model(renamed_relation_group_type_ref_1DB).Updates(*renamed_relation_group_type_ref_1DB)
		if query.Error != nil {
			log.Fatal(query.Error)
		}
	}

}

// BackRepoRenamed_RELATION_GROUP_TYPE_REF_1.ResetReversePointers commits all staged instances of Renamed_RELATION_GROUP_TYPE_REF_1 to the BackRepo
// Phase Two is the update of instance with the field in the database
func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) ResetReversePointers(backRepo *BackRepoStruct) (Error error) {

	for idx, renamed_relation_group_type_ref_1 := range backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1Ptr {
		backRepoRenamed_RELATION_GROUP_TYPE_REF_1.ResetReversePointersInstance(backRepo, idx, renamed_relation_group_type_ref_1)
	}

	return
}

func (backRepoRenamed_RELATION_GROUP_TYPE_REF_1 *BackRepoRenamed_RELATION_GROUP_TYPE_REF_1Struct) ResetReversePointersInstance(backRepo *BackRepoStruct, idx uint, renamed_relation_group_type_ref_1 *models.Renamed_RELATION_GROUP_TYPE_REF_1) (Error error) {

	// fetch matching renamed_relation_group_type_ref_1DB
	if renamed_relation_group_type_ref_1DB, ok := backRepoRenamed_RELATION_GROUP_TYPE_REF_1.Map_Renamed_RELATION_GROUP_TYPE_REF_1DBID_Renamed_RELATION_GROUP_TYPE_REF_1DB[idx]; ok {
		_ = renamed_relation_group_type_ref_1DB // to avoid unused variable error if there are no reverse to reset

		// insertion point for reverse pointers reset
		// end of insertion point for reverse pointers reset
	}

	return
}

// this field is used during the restauration process.
// it stores the ID at the backup time and is used for renumbering
var BackRepoRenamed_RELATION_GROUP_TYPE_REF_1id_atBckpTime_newID map[uint]uint
