// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { BookDetailsGroupAPI } from './bookdetailsgroup-api'
import { BookDetailsGroup, CopyBookDetailsGroupToBookDetailsGroupAPI } from './bookdetailsgroup'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class BookDetailsGroupService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  BookDetailsGroupServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private bookdetailsgroupsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.bookdetailsgroupsUrl = origin + '/api/github.com/fullstack-lang/gongxsd/test/books/go/v1/bookdetailsgroups';
  }

  /** GET bookdetailsgroups from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI[]> {
    return this.getBookDetailsGroups(GONG__StackPath, frontRepo)
  }
  getBookDetailsGroups(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<BookDetailsGroupAPI[]>(this.bookdetailsgroupsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<BookDetailsGroupAPI[]>('getBookDetailsGroups', []))
      );
  }

  /** GET bookdetailsgroup by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI> {
    return this.getBookDetailsGroup(id, GONG__StackPath, frontRepo)
  }
  getBookDetailsGroup(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.bookdetailsgroupsUrl}/${id}`;
    return this.http.get<BookDetailsGroupAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched bookdetailsgroup id=${id}`)),
      catchError(this.handleError<BookDetailsGroupAPI>(`getBookDetailsGroup id=${id}`))
    );
  }

  // postFront copy bookdetailsgroup to a version with encoded pointers and post to the back
  postFront(bookdetailsgroup: BookDetailsGroup, GONG__StackPath: string): Observable<BookDetailsGroupAPI> {
    let bookdetailsgroupAPI = new BookDetailsGroupAPI
    CopyBookDetailsGroupToBookDetailsGroupAPI(bookdetailsgroup, bookdetailsgroupAPI)
    const id = typeof bookdetailsgroupAPI === 'number' ? bookdetailsgroupAPI : bookdetailsgroupAPI.ID
    const url = `${this.bookdetailsgroupsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BookDetailsGroupAPI>(url, bookdetailsgroupAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BookDetailsGroupAPI>('postBookDetailsGroup'))
    );
  }
  
  /** POST: add a new bookdetailsgroup to the server */
  post(bookdetailsgroupdb: BookDetailsGroupAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI> {
    return this.postBookDetailsGroup(bookdetailsgroupdb, GONG__StackPath, frontRepo)
  }
  postBookDetailsGroup(bookdetailsgroupdb: BookDetailsGroupAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BookDetailsGroupAPI>(this.bookdetailsgroupsUrl, bookdetailsgroupdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted bookdetailsgroupdb id=${bookdetailsgroupdb.ID}`)
      }),
      catchError(this.handleError<BookDetailsGroupAPI>('postBookDetailsGroup'))
    );
  }

  /** DELETE: delete the bookdetailsgroupdb from the server */
  delete(bookdetailsgroupdb: BookDetailsGroupAPI | number, GONG__StackPath: string): Observable<BookDetailsGroupAPI> {
    return this.deleteBookDetailsGroup(bookdetailsgroupdb, GONG__StackPath)
  }
  deleteBookDetailsGroup(bookdetailsgroupdb: BookDetailsGroupAPI | number, GONG__StackPath: string): Observable<BookDetailsGroupAPI> {
    const id = typeof bookdetailsgroupdb === 'number' ? bookdetailsgroupdb : bookdetailsgroupdb.ID;
    const url = `${this.bookdetailsgroupsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<BookDetailsGroupAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted bookdetailsgroupdb id=${id}`)),
      catchError(this.handleError<BookDetailsGroupAPI>('deleteBookDetailsGroup'))
    );
  }

  // updateFront copy bookdetailsgroup to a version with encoded pointers and update to the back
  updateFront(bookdetailsgroup: BookDetailsGroup, GONG__StackPath: string): Observable<BookDetailsGroupAPI> {
    let bookdetailsgroupAPI = new BookDetailsGroupAPI
    CopyBookDetailsGroupToBookDetailsGroupAPI(bookdetailsgroup, bookdetailsgroupAPI)
    const id = typeof bookdetailsgroupAPI === 'number' ? bookdetailsgroupAPI : bookdetailsgroupAPI.ID
    const url = `${this.bookdetailsgroupsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<BookDetailsGroupAPI>(url, bookdetailsgroupAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<BookDetailsGroupAPI>('updateBookDetailsGroup'))
    );
  }

  /** PUT: update the bookdetailsgroupdb on the server */
  update(bookdetailsgroupdb: BookDetailsGroupAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI> {
    return this.updateBookDetailsGroup(bookdetailsgroupdb, GONG__StackPath, frontRepo)
  }
  updateBookDetailsGroup(bookdetailsgroupdb: BookDetailsGroupAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BookDetailsGroupAPI> {
    const id = typeof bookdetailsgroupdb === 'number' ? bookdetailsgroupdb : bookdetailsgroupdb.ID;
    const url = `${this.bookdetailsgroupsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<BookDetailsGroupAPI>(url, bookdetailsgroupdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated bookdetailsgroupdb id=${bookdetailsgroupdb.ID}`)
      }),
      catchError(this.handleError<BookDetailsGroupAPI>('updateBookDetailsGroup'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in BookDetailsGroupService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("BookDetailsGroupService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
